### ISSUE TITLE
Use of django Forms in a REST library

### ISSUE THREAD

**Issue by philippeluickx** [Tivix/django-rest-auth#101]
Just wondering if this library would be cleaner if no django forms were used.
Form validation should be replaced by serializer validation. Frontend validation is the responsability of the developer.

What's your opinion?

**Comment by saritasa** [comment]
+1 and agree with @philippeluickx

**Comment by ron8mcr** [comment]
[This PR](https://github.com/Tivix/django-rest-auth/pull/130) solves this issue

**Comment by mariodev** [comment]
#151 merged. Closing.
