### ISSUE TITLE
non_field_errors : Must include email and password HTTP 400

### ISSUE THREAD

**Issue by Mystec** [Tivix/django-rest-auth#103]
After registering a user, I can't login with that user - neither on the AngularJS app nor the JQuery demo app. I followed the Demo instructions verbatim here - http://django-rest-auth.readthedocs.org/en/latest/demo.html

API Response: 400 BAD REQUEST
Content: {"non_field_errors":["Must include \"email\" and \"password\"."]}

How can I login/register a user?

**Comment by nerogit** [comment]
I have same problem,too

**Comment by ajaynayak** [comment]
It looks like the LoginSerializer is using email authentication. You'll need to add the following to settings.py:

ACCOUNT_AUTHENTICATION_METHOD = 'username'

**Comment by Mystec** [comment]
Thank  you!! This fixed the issue.

**Comment by guilmarc** [comment]
But on the current release there is no settings.py.  What can I do ?

**Comment by guilmarc** [comment]
But in the current version there's no settings.py file.  What can I do ?
