### ISSUE TITLE
link in confirmation email not working

### ISSUE THREAD

**Issue by gladsonvm** [Tivix/django-rest-auth#104]
Hi,
First I would like to appreciate the effort you put into this pluggable app which provides easy integration. While registering a new user with api, email is sent but on clicking the link its not confirming the user. Link looks like as given below
 
http://localhost:8000/rest-auth/registration/account-confirm-email/tms6khpwpolzwpao5oruac0amiizcc6vdnevq5lb4iruukkqeveeojx2znsclvug/
and the above link redirects me to 
http://localhost:8000/rest-auth/registration/account-confirm-email/tms6khpwpolzwpao5oruac0amiizcc6vdnevq5lb4iruukkqeveeojx2znsclvug/
and my homepage is loaded.

I tried changing /rest-auth/registration to accounts/confirm-email and got allauth confirm email page but confirm button click redirects me to the second link mentioned, However emails are not confirmed. I verified it by trying logging in using rest auth and got an email not verified response :) 
 I use default settings as per the documentation for installed apps and urls.py. How can I confirm the email using rest auth?

**Comment by gladsonvm** [comment]
I have managed to resolve this issue by mapping allauth confirm view to rest auth confirm email view

 ```python
from allauth.account.views import confirm_email as allauthemailconfirmation
....
url(r'^rest-auth/registration/account-confirm-email/(?P<key>\w+)/$', allauthemailconfirmation, name="account_confirm_email"),
```

It would be helpful if you mention any issues if any using this code like if this is not the right (standard) way. :)

**Comment by mariodev** [comment]
This issue was explained in the FAQ section:
https://github.com/Tivix/django-rest-auth/blob/master/docs/faq.rst
