### ISSUE TITLE
Python3: reset password doesn't work when user model has UUID PK

### ISSUE THREAD

**Issue by antetna** [Tivix/django-rest-auth#105]
Reset password function doesn't work with user model has  UUID as PK. 

     [25/Sep/2015 14:51:22] ERROR [django.request:256] Internal Server Error: /api/rest- auth/password/reset/confirm/
     Traceback (most recent call last):
       File "venv/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
         return self.cursor.execute(sql, params)
     psycopg2.ProgrammingError: operator does not exist: uuid = bytea
     LINE 1: ...customauth_myuser" WHERE "customauth_myuser"."id" = '\x34353...

It's possible this is related to Python3 and maybe PostgreSQL database, problematic code is in serializers.py:

           # ERROR: uid is bytestring and raises error with postgresql
           ... 
           uid = uid_decoder(attrs['uid'])
           self.user = UserModel._default_manager.get(pk=uid)
           ...

           # FIX: making it string and error is gone
            ....
            from django.utils.encoding import force_text
            uid = force_text(uid_decoder(attrs['uid']))
            self.user = UserModel._default_manager.get(pk=uid)
            ...

**Comment by mariodev** [comment]
Thanks for pointing this out. Will be fixed in upcoming version (0.6.0).
