### ISSUE TITLE
demo syncdb error

### ISSUE THREAD

**Issue by nordbit** [Tivix/django-rest-auth#108]
```
django.db.migrations.graph.NodeNotFoundError: Migration account.0003_merge dependencies reference nonexistent parent node ('account', '0002_email_max_length'
```
demo at syncdb

**Comment by mariodev** [comment]
Looks more like a problem with django-allauth. Please try upgrading it and check if that solves the issue. 
If not, then let us now exactly which version of django-allauth and django-rest-auth do you use. Thanks!
