### ISSUE TITLE
Cant authenticate with basic Auth credentials in /login/

### ISSUE THREAD

**Issue by ahuacan** [Tivix/django-rest-auth#109]
Hi! I i am new to django-rest-auth and apis. 
Its the first time i build a rest auth and i am not very familiar with Authorization headers and Content Types.

I am trying to understand why when i try to authenticate a user in /login/ with Basic Authorization like this:
curl -X POST -H "Authorization: Basic dXNlcm5hbWU6cGFzc3dvcmQ="  'https://myurl.com/rest-auth/login/' --insecure

i got this error message:
{"password":["(This field is required"]}

When passing the username and password in the body like this:
curl -X POST -H "Content-Type: application/x-www-form-urlencoded" -d 'username=myuser&password=mypassword' 'https://myurl.com/rest-auth/login/'  --insecure
I got the key:
{"key":"b5c0f3a9c7b2fc2f58a74b25f816e2968c64712f"}

Why this is happening?

I also wonder why when trying the same in /user/ it didnt throw me any error and give me my user model serialized

curl -X GET -H "Authorization: Basic dXNlcm5hbWU6cGFzc3dvcmQ=" -H "Cache-Control: no-cache" 'https://myurl.com/rest-auth/user/' --insecure

The only difference i can understand is that in /login i am using POST and in /user/ is GET

Can anybody explain this to me?

Thanks for reading!

**Comment by cesaringo** [comment]
you dont need to send the Authorization  header on /login 
otherwhise in /user/ the Authorization header is how the user is retrieved from the database

**Comment by mariodev** [comment]
You don't use `/login` in case of basic authentication type.
`Authorization: Basic dXNlcm5hbWU6cGFzc3dvcmQ=` are already your valid credentials that you use to access any protected endpoints (that's exactly why your second endpoint worked)

Please refer to [DRF's authentication](http://www.django-rest-framework.org/api-guide/authentication/) section for more details.
