### ISSUE TITLE
Context processors in Allauth >0.21

### ISSUE THREAD

**Issue by dbrgn** [Tivix/django-rest-auth#114]
As you can see in the changelog (http://django-allauth.readthedocs.org/en/latest/changelog.html#from-0-21-0), django-allauth does not use context processors anymore.

The installation docs (http://django-rest-auth.readthedocs.org/en/latest/installation.html) still list the following:

> Add allauth.socialaccount.context_processors.socialaccount to TEMPLATE_CONTEXT_PROCESSORS in django settings

Can we simply remove the context processor, or is the current version of django-rest-auth incompatible with the current allauth version?

**Comment by mariodev** [comment]
Thank you for noticing! We will remove both of these in upcoming version.
For now you can remove them by yourself without expecting any side effects.
