### ISSUE TITLE
CSRF error and email error

### ISSUE THREAD

**Issue by guocheng** [Tivix/django-rest-auth#116]
I tried the demo, the first error I got was a CSRF error when I went to the **127.0.0.1:8000/login/** page. So I went ahead and added the following in the **login_form.html** template file:

```
{% csrf_token %}
```

Then I tried to login again, and got the following error:

```
API Response: 400 BAD REQUEST
Content: {"non_field_errors":["Must include \"email\" and \"password\"."]}
```

So I used the postman plugin for chrome and entered the email address. Then, I got this error:

{"non_field_errors":["Unable to log in with provided credentials."]}

What did I do wrong?

**Comment by guocheng** [comment]
Ok, I solved it:

First, add `{% csrf_token %}` to **login_form.html** :

```
<form class="form-horizontal ajax-post" role="form" action="{% url 'rest_login' %}">
{% csrf_token %}
```

Then, go to **django-rest-auth/demo/demo/settings.py** change line 105 to 107 to:

```
ACCOUNT_EMAIL_REQUIRED = False
ACCOUNT_AUTHENTICATION_METHOD = 'username'
# ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
```

Then the login demo works.

**Comment by knaperek** [comment]
Should this change be accepted? How about creating a PR for this?

**Comment by guocheng** [comment]
ok I will create a PR for this.

**Comment by mariodev** [comment]
Closing due to provided fix. Thanks @WilliamQLiu !

**Comment by WilliamQLiu** [comment]
Thanks to @guocheng for the detailed description and solution.
