### ISSUE TITLE
Login does not work in Demo project

### ISSUE THREAD

**Issue by knaperek** [Tivix/django-rest-auth#117]
Following the standard registration process, with successful email verification, I'm unable to log in afterwards. Tried giving both username and email in the username field, always the same result:

API Response: 400 BAD REQUEST
Content: {"non_field_errors":["Must include \"email\" and \"password\"."]}

**Comment by guocheng** [comment]
see my thread: https://github.com/Tivix/django-rest-auth/issues/116
