### ISSUE TITLE
django 1.9 and DRF 3.3 compat

### ISSUE THREAD

**Issue by auvipy** [Tivix/django-rest-auth#120]

**Comment by dashmug** [comment]
@auvipy What specific issues are you referring to?

For the deprecation warnings on Django 1.9, I have submitted PR #134. 

What problems are you having with DRF 3.3?

**Comment by smills2929** [comment]
What kind of time-frame are we looking at for a new version with this PR included?

**Comment by mariodev** [comment]
No feedback. Closing.
