### ISSUE TITLE
Optimizing rest-auth/user ORM queries

### ISSUE THREAD

**Issue by mbarszcz** [Tivix/django-rest-auth#124]
Hi,

I'd like to serialize related objects in rest-auth/user view but I'm ending up with many database queries. In a regular DRF view, I'd change queryset to use select_related and prefetch_related. Is there any official way to replace the rest-auth/user view with my own? Or is there a better way to solve this problem?

Cheers,
Matt

**Comment by mariodev** [comment]
Not sure sure exactly what is your problem, since user endpoint is only retrieving user object. Can you give more details on what are these multiple queries? Thanks.

**Comment by mbarszcz** [comment]
I have a custom User model and User serializer that includes some related objects, so my user endpoint doesn't fetch just user object - it fetches, for example, details of the group that the user is a member of.

**Comment by mariodev** [comment]
You will need to override both view and serializer class. We don't provide any magical settings in this case.
