### ISSUE TITLE
password reset view respond ''success" when the email does not belong to a user

### ISSUE THREAD

**Issue by ZachLiuGIS** [Tivix/django-rest-auth#125]
If I call the password reset api view with an email that does not belong to any user, the api still respond with {"success": "Password reset e-mail has been sent."}, and so no email will be sent and users will not know if they forget which email they used in registration.

**Comment by mariodev** [comment]
Thanks for catching this issue. Fixed code will be included in the new 0.6.0 version.

**Comment by LeonardoGentile** [comment]
I might be wrong but it seems this is still happening using the latest development version (commit 00415301d6)

**Comment by pejirout** [comment]
Please reopen, this is still an issue with the newest release (0.9.0). When calling a password reset API endpoint with an e-mail that is not associated with a user,  200_OK is sent with a following message:
{ "detail": "Password reset e-mail has been sent." }

**Comment by youneschaoui** [comment]
reopen this, same problem here

**Comment by nancyhawa** [comment]
Same issue here...

**Comment by noviluni** [comment]
I think that is better to response 200, always. A reset system never should tell you if that e-mail exists or not in the database. Otherwise, everyone could know if some third party email has been used in your website. And that's not a good idea.
