### ISSUE TITLE
Login on registration

### ISSUE THREAD

**Issue by andretietz** [Tivix/django-rest-auth#128]
Hey there,

I am not sure if that's a good solution. When I register right now, I get an access key immediately, even though, I did not verify my email. (afaik, before you were returning the just created user, which sounds reasonable to me)

This causes several problems in my project. (besides the other registration problem #123 )
i.e. I never had to use the 'rest_framework.authtoken' in INSTALLED_APPS (since I am using allauth for the login), now I do need to use it and have to add the token tables, even though, I don't need them

Are you planning to change this in the future?

**Comment by saritasa** [comment]
hi Andre,

I actually like that token is returned on registration (no need for additional API call), you can restrict what can be done with permission classes to given API endpoints

**Comment by andretietz** [comment]
I know, but I have to have 'rest_framework.authtoken' in my installed apps even though I don't need it. before I could optionally remove it. this was better imho

**Comment by philippeluickx** [comment]
Isn't that something that you can manage through allauth settings?
If I remember correctly, there is a setting where you can say email verification is mandatory. I am assuming that rest-auth takes this into account?

http://django-allauth.readthedocs.org/en/latest/configuration.html

ACCOUNT_EMAIL_VERIFICATION (=”optional”)
Determines the e-mail verification method during signup – choose one of “mandatory”, “optional”, or “none”. When set to “mandatory” the user is blocked from logging in until the email address is verified. Choose “optional” or “none” to allow logins with an unverified e-mail address. In case of “optional”, the e-mail verification mail is still sent, whereas in case of “none” no e-mail verification mails are sent.

**Comment by mariodev** [comment]
@andretietz The upcoming version (0.7.0) will support custom token key generation. Also mandatory key would not be displayed inside registration response in case of mandatory verification. Hopefully all of these changes will resolve your issue.
