### ISSUE TITLE
PasswordResetSerializer.validate_email() should not raise when no matching user are found

### ISSUE THREAD

**Issue by jlirochon** [Tivix/django-rest-auth#131]
A 400 response status exposes whether there is a user matching a given email in the database. This is a leak of sensitive data.

I think it's more secure to reply with a 200 status, saying "Ok, if someone matches, he will receive an email"

At least, this behavior could be optional.

**Comment by tdyer-aio** [comment]
agreed! i have overridden this in my use case.

**Comment by mariodev** [comment]
@jlirochon You're right. Thank you for noticing this issue. @mdentremont fix has already been merged.
