### ISSUE TITLE
Use of deprecated django.conf.urls.patterns() (removed in 1.10).

### ISSUE THREAD

**Issue by sully90h** [Tivix/django-rest-auth#136]
Greetings,

The urls.py files use django.conf.urls.patterns(), which triggers the following deprecation warnings in Django 1.9:

    /rest_auth/urls.py:20: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and
    will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url()
    instances instead.

    /rest_auth/registration/urls.py:23: RemovedInDjango110Warning: django.conf.urls.patterns() is 
    deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of 
    django.conf.urls.url() instances instead.

**Comment by dashmug** [comment]
There's a PR for this: #134

**Comment by ubaldino** [comment]
change  /Users/ubaldino/umss/lib/python3.5/site-packages/rest_auth/urls.py  urls content  to:

 urlpatterns = [
      # URLs that do not require a session or valid token
     url(r'^password/reset/', PasswordResetView.as_view(),
          name='rest_password_reset'),
      url(r'^password/reset/confirm/', PasswordResetConfirmView.as_view(),
          name='rest_password_reset_confirm'),
      url(r'^login/', LoginView.as_view(), name='rest_login'),
      # URLs that require a user to be logged in with a valid session / token.
      url(r'^logout/', LogoutView.as_view(), name='rest_logout'),
      url(r'^user/', UserDetailsView.as_view(), name='rest_user_details'),
      url(r'^password/change/', PasswordChangeView.as_view(),
          name='rest_password_change'),
 ]
