### ISSUE TITLE
Improperly configured on email verification

### ISSUE THREAD

**Issue by chubz** [Tivix/django-rest-auth#15]
Hi, I really like this project!
I'd like to see a better explained integration or maybe even some test project like one I'm putting together now, plain latest installs of django/drf/allauth and rest-auth

I've setup a mini project on which I get:
ImproperlyConfigured at /rest-auth/registration/account-confirm-email/<generatedkeyhere>/

The thing is: 
https://github.com/Tivix/django-rest-auth/blob/master/rest_auth/registration/urls.py#L12
has a TemplateView initialized wihout a template. So this should break!

Do we need to override and provide custom verification logic for this process?

**Comment by gorros** [comment]
I use ConfirmEmailView view for email verification, but 'rest-auth/login' allows user to login and obtain access token even without verifying email, however email verification is set to mandatory.

**Comment by NabeelValapra** [comment]
What is the best way to override?

**Comment by ZoltanOnody** [comment]
@mateusz-sikora https://github.com/Tivix/django-rest-auth/blob/master/rest_auth/registration/urls.py#L20 I'd remove there the `#L190` suffix in URL, because the file it links to was changed so it's a little bit confusing that `ConfirmEmailView` is not there but 30 lines bellow.

**Comment by Shelagh-Lewins** [comment]
"If you don't want to use API here, then just use view from djang-allauth https://github.com/pennersr/django-allauth/blob/master/allauth/account/views.py#L190"

I can't find any accurate information about how to use the allauth view? I've tried this:

```
from allauth.account.views import confirm_email

urlpatterns = [
    url(r"^registration/account-confirm-email/(?P<key>[-:\w]+)/$", confirm_email,
        name="account_confirm_email"),
...
]
```

and I get a server error (500) with no further information.

Instructions valid for Django 2 would be really useful.

**Comment by muhammadanas70** [comment]
Hello,

Just refer this Demo. It working for me. 

https://github.com/MuhammadAnas47/django-rest-auth/tree/master/demo
