### ISSUE TITLE
Allow passing options to views as per the django.contrib.auth.views equivalents

### ISSUE THREAD

**Issue by johtso** [Tivix/django-rest-auth#155]
As far as I can see, you can't currently do things like setting a custom email template for password resets. With the standard django view, this can be achieved by passing options to the view.

Could a similar API be exposed for django rest auth's views?

**Comment by mariodev** [comment]
@johtso You can simply override `save` method of [`PasswordResetSerializer`](https://github.com/Tivix/django-rest-auth/blob/master/rest_auth/serializers.py#L133) and hook it up as custom serializer. Inside `save` method you have the possibility to set your own options.

**Comment by johtso** [comment]
Okay, I suppose that'll do, does feel like you have to dig a little deep for quite a common configuration though.
