### ISSUE TITLE
JSON API login 

### ISSUE THREAD

**Issue by nonovd** [Tivix/django-rest-auth#158]
When I try to log in, I get a HTTP 409 CONFLICT response :

```json
{
"errors":{
"detail": "The resource object's type (User) is not the type that constitute the collection represented by the endpoint (LoginView)."
}
}
```

I use https://github.com/django-json-api/django-rest-framework-json-api on top of DRF.

```json
{
  "data": {
    "type": "User",
    "id": null,
    "attributes": {
      "username": "...",
      "password": "..."
    }
  }
}
```
What type should I put ? Thank you.

**Comment by Akay7** [comment]
Maybe that error generated by  https://github.com/django-json-api/django-rest-framework-json-api ?

You can try make that django-rest-framework-json-api ignore login view.
Or write custom serializer for login view, which will not return a error.

**Comment by nonovd** [comment]
Thanks @Akay7 

I found the right type, it was just "LoginView"... Usually the type is the name of the model when you use a ModelViewSet but the LoginView extends GenericAPIView.
