### ISSUE TITLE
CSRF Failed: CSRF token missing or incorrect.

### ISSUE THREAD

**Issue by marcosantonocito** [Tivix/django-rest-auth#16]
Hi,

Thanks for your work! I'm using django-rest-auth, I followed all the steps to implement it but for the following endpoints I get a "CSRF Failed: CSRF token missing or incorrect.":

/rest-auth/logout/ (POST)
/rest-auth/user/ (PUT/PATCH)

I've already implemented TokenAuthentication for Django Rest Framework, what I should do now?

**Comment by deepak1725** [comment]
Anyone facing the same problem, then try including this in settings.py:

`REST_FRAMEWORK = {  

    'DEFAULT_AUTHENTICATION_CLASSES': [
            'rest_framework_jwt.authentication.JSONWebTokenAuthentication',
    ],

    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ]
}`
