### ISSUE TITLE
Issue with Cookies module for angular 1.4+

### ISSUE THREAD

**Issue by adimux** [Tivix/django-rest-auth#160]
The cookies aren't stored in the browser when we use angular 1.4+ simply by using $cookies.var = value
https://docs.angularjs.org/api/ngCookies/service/$cookies
We have to use $cookies.get(name) and $cookies.put(name, value, [options])

**Comment by mariodev** [comment]
@adimux This issue is not directly related to django-rest-auth. Closing.

**Comment by Akay7** [comment]
Which trouble with cookie you have, maybe I can help you. We use angular too with django-rest-auth

**Comment by adimux** [comment]
It is related, because the key is not stored in the cookies. And thus, django-rest-auth is not aware that the user is already connected if the page is reloaded.

**Comment by Akay7** [comment]
@adimux feel free do with this key what you like. If you want save key from default auth serializer to cookie and then reuse it in angular app, you must integrate key more closely to angular. 
Actually you can use default auth by cookie for this case.
