### ISSUE TITLE
No API Endpoint for demo webapp. 

### ISSUE THREAD

**Issue by fergyfresh** [Tivix/django-rest-auth#166]
Basically you can login and logout via the demo web app, but only the Login and the other methods are provided explicitly. It was just something I noticed that isn't a big deal, but I would write code to make it happen and submit a pull.

I would open a PR to add a Logout page to the demo project. It is possible to logout from the current demo all it requires is for you to know you have to POST with a json token '{"token":"very_long_api_token"}' in the content of the post. I just think it would be easier if there was a Logout API endpoint in the demo similar to the token usage to get user details in the 'User Details' API Endpoint.

**Comment by mariodev** [comment]
@fergyfresh Thank you for noticing. Your PR for this issue would be very welcomed :)

**Comment by fergyfresh** [comment]
PR #167 Fixes this issue. 
_/(^_^)\_ (>^_^)> <(^_^<) ^(^_^)^ 
_/(^_^)\_ (>^_^)> <(^_^<) ^(^_^)^ 
_/(^_^)\_ (>^_^)> <(^_^<) ^(^_^)^ 
_/(^_^)\_ (>^_^)> <(^_^<) ^(^_^)^

**Comment by mjaworski** [comment]
Merged PR
