### ISSUE TITLE
Wrong name mentioned in the documentation for REST_AUTH_REGISTER_SERIALIZERS

### ISSUE THREAD

**Issue by n4cr** [Tivix/django-rest-auth#179]
In the package `rest_auth.registration.app_settings`
serializers = getattr(settings, 'REST_AUTH_REGISTER_SERIALIZERS', {})

however in the documentation it is called `REST_AUTH_REGISTRATION_SERIALIZERS`.

**Comment by mariodev** [comment]
Merged #182

**Comment by mrooney** [comment]
Thanks for the fix, but still showing up at http://django-rest-auth.readthedocs.org/en/latest/configuration.html incorrectly :[
