### ISSUE TITLE
Release 0.8.0

### ISSUE THREAD

**Issue by jgr3go** [Tivix/django-rest-auth#185]
0.8.0 was merged in #147, but hasn't been tagged in github & released on pypi (or docs generated).  I don't think I have the permissions to do so, so this is just to track when it's complete.

**Comment by cho-is** [comment]
nice one

**Comment by tention** [comment]
@mariodev please help for the release?

**Comment by tention** [comment]
in case anyone need it, you can install the latest merged development package with this command

pip install https://github.com/Tivix/django-rest-auth/tarball/master

**Comment by tarkatronic** [comment]
This is pretty big for me as well. Is there anything that can be done to assist with this release? Anybody from Tivix who can be pinged, perhaps?

**Comment by shantanugoel** [comment]
Could you please help tag a pypi release for it, @mariodev?

**Comment by flxfxp** [comment]
Ping!

**Comment by philippeluickx** [comment]
+1

**Comment by RobChooses** [comment]
+1

**Comment by stantond** [comment]
Any news?

**Comment by chubz** [comment]
@mateusz-sikora ?

**Comment by mbaragiola** [comment]
Is Tivix MIA?

**Comment by jgr3go** [comment]
@mariodev has been helping merge all pulls. Do you also have access to publish to pypi?  Or know who does?

**Comment by mariodev** [comment]
v0.8.0 released on pypi.
