### ISSUE TITLE
Django < 1.7

### ISSUE THREAD

**Issue by marcosschroh** [Tivix/django-rest-auth#193]
Does the application works with a django version < 1.7?

**Comment by Akay7** [comment]
Anyway you can try. I guess it will have some troubles with migrations. Also you can make fork of this project. And ask questions like this on stackowerflow

**Comment by mariodev** [comment]
@marcosschroh No it doesn't. Django 1.6 is no longer supported. So we've decided to drop it as well.

**Comment by marcosschroh** [comment]
@mariodev I've tested the latest version of your app with Django 1.6.5 and it's working well. The problem is that when you download it, one requirement is Django >= 1.7, so you be forced to use the latest django version. Of course you can install another if you want, but I think you should delete the django dependency, like Django Rest Framework does, and the user will be free to install the version that he/she wants.
