### ISSUE TITLE
url_endpoints length on password reset is wrong length

### ISSUE THREAD

**Issue by jheld** [Tivix/django-rest-auth#194]
I'm not sure how this is occurring, but:

I have basically copied your new_password_confirm html from the demo for my purposes. Just the confirm webpage (and associated templates) so that I can use your reset password logic.

However, my pathname split has length 5, not 6. Length 5 does still work, such that the javascript fills the fields and I can update my password.

Just letting you know!

I installed this directly from pip (0.7.0) and then took the demo code from here against master.

I don't have a lot of bandwidth right now to help you debug, but if you'd be willing to wait and want my help, I'd like to help!

Thanks for the library :)

**Comment by Akay7** [comment]
Do use Django 1.9 with password strength verification(which you have out from the box)? Or you have some custom logic about password strength verification?

**Comment by jheld** [comment]
I phrased the question wrong, and now I've figured out why it's that way.

Your urlpath in the demo has split '/' into length 6. But I have a different URI for resetting the password (the webpage in this case), which is length 5. So, this is moot. My question was about the URI path location, just to clarify. But thank you for responding -- helped me ensure this isn't a bug.
