### ISSUE TITLE
Facebook Code

### ISSUE THREAD

**Issue by vasco-santos** [Tivix/django-rest-auth#203]
What is the code in the /rest-auth/facebook/ (POST)?

**Comment by vasco-santos** [comment]
First of all, you need to create a Facebook Application in the developers page. You will get a Facebook app code and a secret.

For using the /rest-auth/facebook/ method from the django-rest-auth, you need to send the access code (obtained using the javascript SDK) and the code of the Facebook Application.

Finally, before using this method, you have to go the the application back-office and create a social application, using the Facebook app code and the secret.

**Comment by lightninglu10** [comment]
What is this code you mention?

There's an app ID and a secret. Are you talking about the app ID?

**Comment by devkhan** [comment]
@lightninglu10 The app ID(or client ID) is the code.
