### ISSUE TITLE
Configuration docs error @ registration serializers

### ISSUE THREAD

**Issue by paolostefan** [Tivix/django-rest-auth#204]
In [The configuration docs](http://django-rest-auth.readthedocs.org/en/latest/configuration.html)
the correct setting name for custom registration serializers is `REST_AUTH_REGISTER_SERIALIZERS` and not `REST_AUTH_REGISTRATION_SERIALIZERS` (at least that's what `rest_auth/registration/app_settings.py` looks for).

**Comment by mariodev** [comment]
Will be resolved in upcoming version. Ref #190
