### ISSUE TITLE
can we use mobile number on login and forgot password

### ISSUE THREAD

**Issue by sanchig** [Tivix/django-rest-auth#208]
I want to use Mobile Number instead of Username or Email. Now a days user want to use mobile number for login and forgot password (we are using SMS api so we are sending otp and then user can register and login. ex. paytm.com login. we need to set sms api settings in setting.py file). I have done this in my frontend but it is not at best. I am doing get Username using mobile number in backend and then pass it to login url. whatever it is not best practice. Can you please add this functionality to this django-rest-auth package. so other developer can use this too. Please give me suggestion if already implemented.

**Comment by Akay7** [comment]
This application realize functionality for login based on email/login + password, you can reuse it. Just change login to phone. 
Like you can see, you use 3rd party libraries, that application based just on django and rest framework. And I more users preferred not add any not necessary functionality(for general purpose of this app - rest-auth) to this application.
If you would add more functionality, you can do this inside your app. Or hired someone for $ who can do this.

**Comment by mariodev** [comment]
What @Akay7 said ;)
