### ISSUE TITLE
django-allauth Forms instead of django.contrib.auth Forms

### ISSUE THREAD

**Issue by girishkumarkh** [Tivix/django-rest-auth#210]
Currently we are using:
https://github.com/Tivix/django-rest-auth/blob/master/rest_auth/serializers.py#L3
`from django.contrib.auth.forms import PasswordResetForm, SetPasswordForm`
can we use
https://github.com/pennersr/django-allauth/blob/master/allauth/account/views.py#L20
`from allauth.forms import PasswordResetForm, SetPasswordForm`

maybe I might be wrong if we are using allauth by default - why can we just use allauth's Forms instead of django's

**Comment by Akay7** [comment]
By default we are not using allauth.

**Comment by girishkumarkh** [comment]
got it!
