### ISSUE TITLE
Documenting responses to auth API endpoints

### ISSUE THREAD

**Issue by pramttl** [Tivix/django-rest-auth#216]
Currently the [endpoint documentation](https://django-rest-auth.readthedocs.io/en/latest/api_endpoints.html), just contains the request types and the input parameters. There is no documentation on the response objects. It would be good to have that included too.

**Comment by pramttl** [comment]
Djoser, which is a similar library also has response documentation: https://github.com/sunscrapers/djoser#endpoints

**Comment by Akay7** [comment]
@pramttl Djoser returning not 403 error for unauth user?

**Comment by maxim-kht** [comment]
Duplicate of https://github.com/Tivix/django-rest-auth/issues/280
