### ISSUE TITLE
django.contrib.sites dependency missing in installation instructions

### ISSUE THREAD

**Issue by hkraal** [Tivix/django-rest-auth#218]
Without
```
INSTALLED_APPS = (
    ...,
    'django.contrib.sites',
```

You will get an "OperationalError: no such table: django_site" when trying to register a user.

```
$ lsb_release -d
Description:    Ubuntu 14.04.4 LTS

$ python --version
Python 3.4.3

$ pip freeze
defusedxml==0.4.1
Django==1.8
django-allauth==0.25.2
django-rest-auth==0.7.0
djangorestframework==3.3.3
oauthlib==1.1.2
python3-openid==3.0.10
requests==2.10.0
requests-oauthlib==0.6.1
six==1.10.0
```

**Comment by Akay7** [comment]
Registration user working only with allauth. In allauth documentation you can read about you must set sites_id and install 'django.contrib.sites'

**Comment by hkraal** [comment]
@Akay7 that's also the case for:

```
INSTALLED_APPS = (
    ...,
    'allauth',
    'allauth.account',
```

However those are in the installation instructions of allauth as well but nevertheless repeated (for clarity sake) in the django-rest-auth installation instructions.

So be consequent I would be inclined to say the `django.contrib.sites` should be mentioned.

**Comment by Akay7** [comment]
@hkraal 
You can update documentation and make pull request
https://github.com/Tivix/django-rest-auth/blob/master/docs/installation.rst
