### ISSUE TITLE
[Q] Token reset ?

### ISSUE THREAD

**Issue by glenfant** [Tivix/django-rest-auth#221]
Hi, is it possible to reset the authentication token for an user without changing the password ? Or did I miss something related in the doc ?
Thanks in advance.

**Comment by Akay7** [comment]
@glenfant  that depend from Token which you want reset, some of them have they own Models and they will still work after change password.

more better ask questions on StackOverflow.

**Comment by mariodev** [comment]
@glenfant You can simply create dedicated view to do that. As @Akay7 mentioned, it's better to ask this on SO if need help on how to do that.
