### ISSUE TITLE
how can i override django-rest-auth options?

### ISSUE THREAD

**Issue by piyushmaurya23** [Tivix/django-rest-auth#223]
in login, i want:
1. email
2. password
3. username(i want to remove it)

in signup
1. first_name & last_name ( i want to add it)
2. username ( i want to remove it)
3. email
4. password

I have same configuration on django-allauth.

**Comment by Akay7** [comment]
You can override login serialiser. For signup you can write custom api view.

**Comment by piyushmaurya23** [comment]
@Akay7 can you give me little more details with code, i am totally new to django. Thank you.

**Comment by Akay7** [comment]
That page have information about which api endpoints you can override http://django-rest-auth.readthedocs.io/en/latest/configuration.html , for login you can use:
` 'LOGIN_SERIALIZER': 'path.to.custom.LoginSerializer', `
For realize custom registration logic and serializer I'm recommend to you read documentation of [drf](http://www.django-rest-framework.org/) .

And in next time if you have questions about how to make something, you can ask that at stackoverflow

**Comment by piyushmaurya23** [comment]
its resolved. thank you @Akay7

**Comment by karthikrajender28** [comment]
Hi Akay7 

I need to use custom registration serializer for my app, now i am using rest-auth register serializer how can i override the register serializer with my custom serializer and what is the setting i need to apply in settings.py file

path of rest auth serializer: rest_auth.registration.serializers.RegisterSerializer

**Comment by Akay7** [comment]
@karthikrajender28 
Try this in your settings.py
`REST_AUTH_REGISTER_SERIALIZERS = {
    'REGISTER_SERIALIZER': 'path.to.your.custom.register.serializer',
}`

docs [here](http://django-rest-auth.readthedocs.io/en/latest/configuration.html?highlight=REST_AUTH_REGISTER_SERIALIZERS)

**Comment by karthikrajender28** [comment]
Hi Akay7

Thank you very much for your comments. it solves my problem.

**Comment by jsoni2** [comment]
Hi @Akay7  I am very new to django. building user authentication API. I need to get user data in response to Django user_auth login Endpoint. How exactly I override Login Serializer? Can you please give an example or something?

TIA.

**Comment by Akay7** [comment]
Hi @jsoni2 
I guess best choice right now is override `get_response_serializer` https://github.com/Tivix/django-rest-auth/blob/master/rest_auth/views.py#L54 in LoginView. 
I'm try to make same for my pet project https://github.com/Akay7/ToDoList/blob/master/backend/user_profile/views.py#L16 
P.S. I'm make PR #328 but it's still not merged.

**Comment by sameergaikwad222** [comment]
Hi I overriden Register Serializer along with my Custom User model. Made changes in Settings file but still getting Username Field in dj-rest-auth registration api end point. Shall i also needs to implement Custom registration form for same ??

**Comment by sameergaikwad222** [comment]
`from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin, AbstractUser
from django.utils import timezone


class UserManager(BaseUserManager):

    def _create_user(self, email, password, is_staff, is_superuser, name, mobileNum, gender, **extra_fields):
        if not email:
            raise ValueError('Users must have an email address')
        now = timezone.now()
        email = self.normalize_email(email)
        user = self.model(
            email=email,
            is_staff=is_staff,
            is_active=True,
            is_superuser=is_superuser,
            last_login=now,
            date_joined=now,
            name=name,
            mobileNum=mobileNum,
            gender=gender,
            **extra_fields
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password, name, mobileNum, gender, **extra_fields):
        return self._create_user(email, password, False, False, name, mobileNum, gender, **extra_fields)

    def create_superuser(self, email, password, name, mobileNum, gender, **extra_fields):
        user = self._create_user(
            email, password, True, True, name, mobileNum, gender, **extra_fields)
        return user


class User(AbstractBaseUser, PermissionsMixin):
    GENDER_CHOICES = [
        ('m', 'Male'),
        ('f', 'Female'),
        ('o', 'Other'),
    ]
    email = models.EmailField(max_length=254, unique=True)
    name = models.CharField(max_length=254, null=True, blank=True)
    mobileNum = models.CharField(
        max_length=10, null=False, blank=False)
    gender = models.CharField(
        max_length=1, choices=GENDER_CHOICES, null=False, blank=False)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    last_login = models.DateTimeField(
        null=True, blank=True)
    date_joined = models.DateTimeField(auto_now_add=True)

    class Meta(AbstractUser.Meta):
        swappable = 'AUTH_USER_MODEL'

    USERNAME_FIELD = 'email'
    EMAIL_FIELD = 'email'
    REQUIRED_FIELDS = ['name', 'mobileNum', 'gender']

    objects = UserManager()

    def get_absolute_url(self):
        return "/samnet/%i/" % (self.pk)
`

**Comment by sameergaikwad222** [comment]
[project.zip](https://github.com/Tivix/django-rest-auth/files/4995987/project.zip)

**Comment by crowded-geek** [comment]
@sameergaikwad222 add `username = None` in your CustomRegisterSerializer, it'll get rid of the username field.
