### ISSUE TITLE
Update readthedocs documentation.

### ISSUE THREAD

**Issue by Darwesh27** [Tivix/django-rest-auth#225]
![rest-auth-ser](https://cloud.githubusercontent.com/assets/4861876/16324673/c5e78266-39cf-11e6-9758-9d0ce9d74421.png)
It still says `REST_AUTH_REGISTRATION_SERIALIZERS`  instead of `REST_AUTH_REGISTER_SERIALIZERS`.

**Comment by mariodev** [comment]
Resolved with latest build.
