### ISSUE TITLE
Add example for authenticated REST API endpoint

### ISSUE THREAD

**Issue by sils** [Tivix/django-rest-auth#228]
Hi,

I'm new to django and think it'd be good to have an example for an authenticated REST API endpoint because usually you want the user to be able to do stuff. Weirdly the demo doesn't seem to contain this and I couldn't find anything in the docs.

**Comment by bernardogontijo** [comment]
@sils1297 have you find any example of this?

**Comment by sils1297** [comment]
Don't think I found an example but I got it working, it was a while ago though I'll definitely need this again. I'm not allowed to share that particular portion of it (was a rather ridiculous project)

**Comment by maxim-kht** [comment]
Hi @sils, please let me know what do you mean by authenticated REST API endpoint. The endpoints that require authentication are `/rest-auth/user/` and `/rest-auth/password/change/`. These endpoints are included in both demo project and are viewable in attached Swagger docs.

**Comment by sils** [comment]
hm, that's helpful but not obvious to find

**Comment by maxim-kht** [comment]
<img width="296" alt="django-rest-auth_demo" src="https://cloud.githubusercontent.com/assets/8700772/21444066/b0181d06-c85e-11e6-8f18-b72b936f9bd8.png">

This is the list of all the endpoints on the demo project. The endpoints that are accessed after the authentication are logically separated from the ones, that are used for the authentication process.

Please let me know where would you include information that would make it more obvious. Thank you!

**Comment by sils** [comment]
Are those the "swagger docs"? I have no idea where to find that (and I don't seem to be the only person). Would be nice to mention that in http://django-rest-auth.readthedocs.io/en/latest/index.html since those are pointed out as the official docs or replace them?

**Comment by sils** [comment]
(Just trying to help here, the problem is solved for me since you provided the info I needed.)

**Comment by maxim-kht** [comment]
Swagger docs were added to the demo project around two months ago.
This was the menu on the demo project http://django-rest-auth.readthedocs.io/en/latest/demo.html. The Swagger docs can be accessed from there as well, by clicking the "API Docs" on the navbar.

We do have information regarding the endpoints here http://django-rest-auth.readthedocs.io/en/latest/api_endpoints.html. Although it is not stated explicitly, the endpoints that allow you to change password or view and update user details would always require authentication.

We will further expand documentation on API endpoint in the future. For now more info can be accessed from https://github.com/Tivix/django-rest-auth/blob/master/rest_auth/views.py. 

Thank you!

**Comment by sils** [comment]
maybe make it obvious that the demo project actually contains docs about
itself that help learning django-rest-auth? Not sure, I'm too tired for
today but thanks so far.

Sincerely,

Lasse Schuirmann

lasse@schuirmann.net
http://coala.io/ - http://viperdev.io/ - http://gitmate.com/

**Comment by maxim-kht** [comment]
>maybe make it obvious that the demo project actually contains docs about
itself that help learning django-rest-auth?

That was the original idea behind including the demo project, as we specified here http://django-rest-auth.readthedocs.io/en/latest/demo.html. 

We will take it into consideration when working further on the documentation.

Thank you for your feedback!
