### ISSUE TITLE
Error with Social Authentication (Facebook): NoReverseMatch: Reverse for 'socialaccount_signup'

### ISSUE THREAD

**Issue by eriol** [Tivix/django-rest-auth#23]
Hello,
I enabled Facebook login following documentation but I'm getting the same error described here:
https://github.com/pennersr/django-allauth/issues/558

What am I missing? Thanks in advance.

**Comment by vesterbaek** [comment]
I'm getting this error when trying to login with a facebook account that has the same email address as an already registered user.

```
Environment:


Request Method: POST
Request URL: http://127.0.0.1:8000/rest-auth/facebook/

Django Version: 1.7.4
Python Version: 2.7.8
Installed Applications:
('django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.sites',
 'rest_framework',
 'rest_framework.authtoken',
 'rest_auth',
 'rest_auth.registration',
 'allauth',
 'allauth.account',
 'allauth.socialaccount',
 'allauth.socialaccount.providers.facebook')
Installed Middleware:
('django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware')


Traceback:
File "/Users/jeppe/djangotest/restauthtest/.virtualenv/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
  111.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/Users/jeppe/djangotest/restauthtest/.virtualenv/lib/python2.7/site-packages/django/views/decorators/csrf.py" in wrapped_view
  57.         return view_func(*args, **kwargs)
File "/Users/jeppe/djangotest/restauthtest/.virtualenv/lib/python2.7/site-packages/django/views/generic/base.py" in view
  69.             return self.dispatch(request, *args, **kwargs)
File "/Users/jeppe/djangotest/restauthtest/.virtualenv/lib/python2.7/site-packages/rest_framework/views.py" in dispatch
  407.             response = self.handle_exception(exc)
File "/Users/jeppe/djangotest/restauthtest/.virtualenv/lib/python2.7/site-packages/rest_framework/views.py" in dispatch
  404.             response = handler(request, *args, **kwargs)
File "/Users/jeppe/djangotest/restauthtest/.virtualenv/lib/python2.7/site-packages/rest_auth/views.py" in post
  51.         if not self.serializer.is_valid():
File "/Users/jeppe/djangotest/restauthtest/.virtualenv/lib/python2.7/site-packages/rest_framework/serializers.py" in is_valid
  186.                 self._validated_data = self.run_validation(self.initial_data)
File "/Users/jeppe/djangotest/restauthtest/.virtualenv/lib/python2.7/site-packages/rest_framework/serializers.py" in run_validation
  367.             value = self.validate(value)
File "/Users/jeppe/djangotest/restauthtest/.virtualenv/lib/python2.7/site-packages/rest_auth/registration/serializers.py" in validate
  36.             complete_social_login(request, login)
File "/Users/jeppe/djangotest/restauthtest/.virtualenv/lib/python2.7/site-packages/allauth/socialaccount/helpers.py" in complete_social_login
  145.         return _complete_social_login(request, sociallogin)
File "/Users/jeppe/djangotest/restauthtest/.virtualenv/lib/python2.7/site-packages/allauth/socialaccount/helpers.py" in _complete_social_login
  161.         ret = _process_signup(request, sociallogin)
File "/Users/jeppe/djangotest/restauthtest/.virtualenv/lib/python2.7/site-packages/allauth/socialaccount/helpers.py" in _process_signup
  28.         url = reverse('socialaccount_signup')
File "/Users/jeppe/djangotest/restauthtest/.virtualenv/lib/python2.7/site-packages/django/core/urlresolvers.py" in reverse
  551.     return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
File "/Users/jeppe/djangotest/restauthtest/.virtualenv/lib/python2.7/site-packages/django/core/urlresolvers.py" in _reverse_with_prefix
  468.                              (lookup_view_s, args, kwargs, len(patterns), patterns))

Exception Type: NoReverseMatch at /rest-auth/facebook/
Exception Value: Reverse for 'socialaccount_signup' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
```

**Comment by mateusz-sikora** [comment]
@vesterbaek Make sure you have `'allauth.socialaccount'` added to your `INSTALLED_APPS`

More about social auth configuration http://django-rest-auth.readthedocs.org/en/latest/installation.html#social-authenitcation-optional

**Comment by vesterbaek** [comment]
Yes, that's already added. This works fine for a facebook user with an email address that's not already registered in django/allauth. In that case, auto signup is not allowed (due to email address unique constraint), causing allauth to try to resolve the socialaccount_signup url name. See here: https://github.com/pennersr/django-allauth/blob/aeecd6caed0053554649a56c1091b549525cccca/allauth/socialaccount/helpers.py#L27

**Comment by mateusz-sikora** [comment]
@vesterbaek see my commit, your are missing this line:
https://github.com/Tivix/django-rest-auth/commit/8182a33c6660c01dce5f32eeedf71f4d23328651#diff-1d260d423859f618e00ad92002a624acR22

**Comment by kishan3** [comment]
I did what @eriol  did up there in settings file. But now my users are getting created without email id !!!
Here is my settings file configuration any help please???

` SOCIALACCOUNT_EMAIL_VERIFICATION = None
    SOCIALACCOUNT_EMAIL_REQUIRED = False
    SOCIALACCOUNT_QUERY_EMAIL = True

    SOCIALACCOUNT_PROVIDERS = {
        'facebook':
            {
                'METHOD': 'oauth2',
                'SCOPE': ['email', 'public_profile', 'user_friends'],
                'AUTH_PARAMS': {'auth_type': 'reauthenticate'},
                'FIELDS': [
                    'id',
                    'email',
                    'name',
                    'first_name',
                    'last_name',
                    'verified',
                    'locale',
                    'timezone',
                    'link',
                    'gender',
                    'updated_time'],
                'EXCHANGE_TOKEN': True,
                'LOCALE_FUNC': lambda request: 'en_US',
                'VERIFIED_EMAIL': False,
            }
    }`

**Comment by sysradium** [comment]
Same here. No idea why email isn't set on `email` model field.

**Comment by sysradium** [comment]
Maybe someone already said that, but django tries to redirect to `socialaccount_signup` if an automatic signup could not be performed.

And this happens if email is not present in the Facebook API response. That can happen even if `email` scope was added. You'll be surprised to find out that email is missing from the Facebook graph response even if `email` is in a scope. I am still digging that, but it seems that it happens if the email on your facebook account isn't verified or something. Double check that.

**Comment by koslibpro** [comment]
Same error in my case. Any updates on this issue?

**Comment by ramsrib** [comment]
This issue doesn't seems to be resolved (I'm facing it too). Can you guys reopen it?

**Comment by ramsrib** [comment]
When the user email already exists, it disables the `auto_signup` and tries to redirect to `socialaccount_signup` url. But it's not configured (based on documentation). So, it fails with the reported error. 

And disabled `SOCIALACCOUNT_EMAIL_VERIFICATION` doesn't seems to be right solution and it doesn't work for me either.

**Comment by ramsrib** [comment]
allauth issue url: https://github.com/pennersr/django-allauth/issues/418

**Comment by emanlodovice** [comment]
If anyone is still experiencing this issue, this happens if you included `allauth.urls` in a `urls.py` that defines an `app_name`.

e.g. authentication/urls.py
```
app_name = "authentication"
urlpatterns = [
    ...
    path("social/", include("allauth.urls", namespace="")),
    ...
]
```
I guess the namespace gets carried over to the included URL???

one solution around this I think is to include  `allauth.urls` in your root urlconf instead.

**Comment by najmathummer21** [comment]
@ramsrib could you please explain the solution?

**Comment by almehady** [comment]
> The problem seems to be related to social account email verification. Relaxing configuration with
> 
> ```
> SOCIALACCOUNT_EMAIL_VERIFICATION = 'none'
> SOCIALACCOUNT_EMAIL_REQUIRED = False
> SOCIALACCOUNT_QUERY_EMAIL = True
> ```
> 
> make it works.

This solved my problem
