### ISSUE TITLE
ImportError: No module named 'allauth'

### ISSUE THREAD

**Issue by Koed00** [Tivix/django-rest-auth#237]
Since the last version, it seems that django-allauth is a dependency again.
Can be fixed by installing django-allauth, but should either be in the requirements or a conditional import.

**Comment by nirizr** [comment]
I came across this as well

**Comment by nirizr** [comment]
Looks like a fix for this is merged. Next release should resolve this.

**Comment by pwhipp** [comment]
Not resolved in 0.8.1

**Comment by nirizr** [comment]
Yes. 0.8.1 is the release (re)introducing this issue. 
Commit 2546b17 (currently only in master) seems to fix it.

**Comment by Akay7** [comment]
My commit fix this, try install this app from master

**Comment by mariodev** [comment]
Fixed in v0.8.2

**Comment by nirizr** [comment]
This should be reopened, as `allauth` is still an implicit requirement.
See views.py line 98 (https://github.com/Tivix/django-rest-auth/blob/master/rest_auth/views.py#L98).

`allauth_settings` is assumed to exist, while it only does if `allauth` is installed.

**Comment by nirizr** [comment]
Thanks for the fast response!

This poses somewhat of a design question (should the setting be duplicated? Should it be ignored when allauth is missing?).

**Comment by maxim-kht** [comment]
@nirizr I checked, and I think it should be opened as a separate issue - currently this endpoint will work, but without allauth and `LOGOUT_ON_GET` setting key it will not allow sending GET request to log out.

Not including `allauth` is not breaking rest_auth endpoints anymore, but we do need to add extra settings key for allowing GET on logout view. I will open separate issue.
