### ISSUE TITLE
UserDetailsSerializer in JWTSerializer

### ISSUE THREAD

**Issue by chubz** [Tivix/django-rest-auth#239]
Hi I've noticed @ https://github.com/Tivix/django-rest-auth/blob/master/rest_auth/serializers.py#L138

Here rest-auth UserDetailsSerializer is used instead of one defined inside settings. Maybe this could be added to 0.8.1 since it would continue already defined behaviour for settin up custom serializers.

This way if anyone is overriding the user details serializer doesn't have to override the JWT serializer aswell.

**Comment by rubberviscous** [comment]
I noticed this issue as well. When using the JWT authentication, the custom USER_DETAILS_SERIALIZER I have defined is ignored and the rest-auth UserDetailsSerializer is used instead.

**Comment by maxim-kht** [comment]
Resolved in latest version
