### ISSUE TITLE
Empty reponse during registration

### ISSUE THREAD

**Issue by chubz** [Tivix/django-rest-auth#240]
Hi,

In the register view I've noticed that there is a allauth setting check around https://github.com/Tivix/django-rest-auth/blob/master/rest_auth/registration/views.py#L36

this checks if email verification is mandatory. Since the registration flow incorporates an email being sent to users email and the allauth default adapter reverses to the account_email_verification_sent url @https://github.com/pennersr/django-allauth/blob/master/allauth/account/adapter.py#L428
 Would it be okay to maybe add either some modifiable message like {'message': 'verification email sent' }
returning an empty {} after the registration feels unfinished.

**Comment by maxim-kht** [comment]
Added the message in the latest version.
