### ISSUE TITLE
on user registration last_login should be None

### ISSUE THREAD

**Issue by sanchig** [Tivix/django-rest-auth#242]
everything works fine but when user register date_joined and last_login date has been set. I think last_login should be set to None on user registration.
I tried to modify def save(self, request): in RegisterSerializer for last_login but doesn't work.

**Comment by sanchig** [comment]
DONE after changes on 
==>site-packages/rest-auth/registration/views.py
`class RegisterView(CreateAPIView):
    def perform_create(self, serializer):
        user = serializer.save(self.request)
        if getattr(settings, 'REST_USE_JWT', False):
            self.token = jwt_encode(user)
        else:
            create_token(self.token_model, user, serializer)

        complete_signup(self.request._request, user,
                        allauth_settings.EMAIL_VERIFICATION,
                        None)
        user.last_login = None
        user.save()
        return user`

**Comment by Akay7** [comment]
User last_login set because function complete_signup of allauth do that line 163 
```
def complete_signup(request, user, email_verification, success_url,
                    signal_kwargs=None):
    if signal_kwargs is None:
        signal_kwargs = {}
    signals.user_signed_up.send(sender=user.__class__,
                                request=request,
                                user=user,
                                **signal_kwargs)
    return perform_login(request, user,
                         email_verification=email_verification,
                         signup=True,
                         redirect_url=success_url,
                         signal_kwargs=signal_kwargs)
```
I'm recommend to you use another way to your goal, then rewrite view in rest-auth app.

**Comment by maxim-kht** [comment]
Closing the ticket since this is a part of allauth logic. Overriding `perform_create()` here is probably the best solution.
