### ISSUE TITLE
Triggering 500 for duplicate emails

### ISSUE THREAD

**Issue by chubz** [Tivix/django-rest-auth#243]
Hi, 

If a project doesn't include allauth.url there is a case when someone using the same email address as local user tries to sign in with SocialAccount and same email address. There is a 500 triggered on social_acount_signup reverse.

I've seen it mentioned in closed issues.

Allauth provides a hook on the adapter pre_social_login.

I've noticed that the only type of exception covered in the SocialLoginSerializer you provide is:

``` #!python
try:
    login = self.get_social_login(adapter, app, token, access_token)
    complete_social_login(request, login)
except HTTPError:
    raise serializers.ValidationError(_('Incorrect value'))
```

This seems like a bad way to intercept anything put in pre_social_login hook. Also there are other errors which could happen in the process to which maybe other messages apply.

Do you guys think there is maybe a better way to go about this?

**Comment by chubz** [comment]
@mariodev or @mateusz-sikora maybe this could catch the HTTPError as intended but also could catch any exception with a generic message like:
Login procces failed.

This could then provide more flexibility and would not require anyone who needs to break the login process to import HTTPError and they could use something meaningful to them.

If you want i could write the addition of another except Exception block there.

Maybe there is a better way?

**Comment by MattBlack85** [comment]
I think here the main problem is how to deal with all the cases a duplicate email would mean. I'm facing the same problem in my project and I had to override the adapters to achieve my result.  There are many cases when one tries to log in via social account and an account already exists:
- do we want to merge the accounts?
- do we want to send a notifications to the user asking if he/she wants to merge the accounts?
- do we want to just send back a message like "sorry, an account with the given email already exists"
- create another `User` with the same email

I'd really like to have some kind of logic to allow choosing between those when using rest-auth

**Comment by chubz** [comment]
@MattBlack85 that is a general problem of having both local account and social account option gives to the project.
Account handking is not done by django-rest-auth. It is done by django-allauth. There are a few issues there, but generally it is left for each project to build and customize via adapter.

Some projects have a policy to never allow social and local accounts to connect, some want them to be connected from inside a logged in user session.

I've started this issue so authors take notice that they are narrowing options for overriding behavior set in the adapter inside the login view.

If you want to throw and attribute error, or a custom exception inside your project from the adapter the view will not catch it.

**Comment by maxim-kht** [comment]
Resolved in https://github.com/Tivix/django-rest-auth/pull/367

Also social connect functionality was added that addresses this issue: http://django-rest-auth.readthedocs.io/en/latest/installation.html#additional-social-connect-views
