### ISSUE TITLE
Got TemplateDoesNotExists in register and password reset in demo project

### ISSUE THREAD

**Issue by tvhong** [Tivix/django-rest-auth#245]
Hi,
I'm trying out the demo project. But when I send requests to register or password reset, I get **TemplateDoesNotExists** for _account/email/email_confirmation_signup_subject.txt_ and _registration/password_reset_subject.txt_ respectively.

This is what I did:
1. Create virtualenv and activate it (for python version 2.7).
2. Follow these instructions to install demo project: http://django-rest-auth.readthedocs.io/en/latest/demo.html
3. Send requests to create new account: `curl -d "username=tom&password1=tom12345&password2=tom12345&email=tom@tom.com" http://localhost:8000/rest-auth/registration/`
4. Receive back error code 500 with error page for TemplateDoesNotExists for template _account/email/email_confirmation_signup_subject.txt_. The account did get created though. 

A quick look on google and that template belongs to django-allauth, so I tried to install it: `pip install django-allauth`. But that didn't solve the problem.

I'm still new to Django so might have missed something trivial. Any help is appreciated.

**Comment by chubz** [comment]
@tvhong you can provide these templates if you override django-allauth templates inside your project.
Another way is to include the allauth app/urls in your project, installing the package doesn't do anything in it self for a django project. You need to add it to your project.

Follow django-allauth setup instructions.

**Comment by trulyliu** [comment]
I met the same exception and revolved it as following.
add following code in demo/settings.py
`TEMPLATES = [
{
    'BACKEND': 'django.template.backends.django.DjangoTemplates',
    'DIRS': [os.path.join(BASE_DIR, 'templates'),],
    'APP_DIRS': True,
    'OPTIONS': {
        'context_processors': [
            'django.template.context_processors.debug',
            'django.template.context_processors.request',
            'django.contrib.auth.context_processors.auth',
            'django.contrib.messages.context_processors.messages',
        ],
    },
},
]
`

And commnets following code out
`
'''
TEMPLATE_CONTEXT_PROCESSORS = (
    'django.contrib.auth.context_processors.auth',
    "django.core.context_processors.request",

    # Disabling due to alluth>=0.21.0 changes
    # "allauth.account.context_processors.account",
    # "allauth.socialaccount.context_processors.socialaccount",
)

TEMPLATE_LOADERS = ('django.template.loaders.filesystem.Loader',
 'django.template.loaders.app_directories.Loader')

TEMPLATE_DIRS = [os.path.join(BASE_DIR, 'templates')]
'''
`

**Comment by maxim-kht** [comment]
Thank you! The above has been added to the demo project settings.

**Comment by Optimization778** [comment]
> Thank you! The above has been added to the demo project settings in 0.8.2.





https://gorgeouswounding.github.io/ElhIZA36QBbykXBUqqz1dn4/
