### ISSUE TITLE
Logged in user should not be able to register an account

### ISSUE THREAD

**Issue by stantond** [Tivix/django-rest-auth#246]
Correct me if I'm wrong (maybe this was a design decision) but I don't think a logged in user should be able to register a new account - we know the user already has an account.

**Comment by chubz** [comment]
@stantond the url for registration has no authentication on it. Therefore it doesn't know if the user is registered or not.
Registration and login urls are usually public so anyone can access them and register an account or provide their username-email/password and authenticate.

The whole user is registered already part of logic should be kept on client side. Either mobile app/angluar front end app or simple CLI app you build.
If you provide the required info to the endpoint and it is valid: username/email or any other unique handler does not collide it should create a user.
