### ISSUE TITLE
rest_framework.exceptions.ValidationError: {'non_field_errors': ['Incorrect value']}

### ISSUE THREAD

**Issue by lightninglu10** [Tivix/django-rest-auth#253]
Hey guys,

I'm trying to do Facebook login, but I don't know what this `code` is that I have to send up. 

I sent the Facebook App ID, but I'm getting `{'non_field_errors': ['Incorrect value']}` for `self.serializer.is_valid(raise_exception=True)`.

What is this?

**Comment by Zowie** [comment]
Hey @lightninglu10! This probably means something is not right in between your app and Facebook. Maybe you configured the wrong app, or your access token is expired :-)

It's being raised in `rest_auth.registration.serializers.py` at line `109`, this is the code where it's being raised:

```
        try:
            login = self.get_social_login(adapter, app, token, access_token)
            complete_social_login(request, login)
        except HTTPError:
            raise serializers.ValidationError(_('Incorrect value'))
```

So: most likely nothing with this package :)

**Comment by maxim-kht** [comment]
Hi @lightninglu10 

Info about Facebook code: https://github.com/Tivix/django-rest-auth/issues/203

Also, latest version now includes additional validation for `code` and `access_token`, and will throw `"Incorrect input. access_token or code is required."` error when both values are either missing or empty. So if you see this response with the latest version, it means that the problem might be with Facebook App ID.

**Comment by hananhafez** [comment]
i have same error with latest version of this library and this error raise when i upgrade django from 1.8 to 1.11 any help plz
