### ISSUE TITLE
ImportError: No module named importlib after install

### ISSUE THREAD

**Issue by briva** [Tivix/django-rest-auth#254]
Hi guys :)

After install django-rest-auth i got this message:

> Traceback (most recent call last):
>   File "manage.py", line 12, in <module>
>     execute_from_command_line(sys.argv)
>   File "lib/djangae/core/management/__init__.py", line 65, in execute_from_command_line
>     return _execute_from_command_line(namespace.sandbox, ['manage.py'] + namespace.args, **overrides)
>   File "lib/djangae/core/management/__init__.py", line 45, in _execute_from_command_line
>     return django_management.execute_from_command_line(argv)
>   File "lib/django/core/management/__init__.py", line 353, in execute_from_command_line
>     utility.execute()
>   File "lib/django/core/management/__init__.py", line 327, in execute
>     django.setup()
>   File "lib/django/__init__.py", line 18, in setup
>     apps.populate(settings.INSTALLED_APPS)
>   File "lib/django/apps/registry.py", line 115, in populate
>     app_config.ready()
>   File "lib/debug_toolbar/apps.py", line 15, in ready
>     dt_settings.patch_all()
>   File "lib/debug_toolbar/settings.py", line 228, in patch_all
>     patch_root_urlconf()
>   File "lib/debug_toolbar/settings.py", line 216, in patch_root_urlconf
>     reverse('djdt:render_panel')
>   File "lib/django/core/urlresolvers.py", line 568, in reverse
>     app_list = resolver.app_dict[ns]
>   File "lib/django/core/urlresolvers.py", line 360, in app_dict
>     self._populate()
>   File "lib/django/core/urlresolvers.py", line 293, in _populate
>     for pattern in reversed(self.url_patterns):
>   File "lib/django/utils/functional.py", line 33, in __get__
>     res = instance.__dict__[self.name] = self.func(instance)
>   File "lib/django/core/urlresolvers.py", line 417, in url_patterns
>     patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
>   File "lib/django/utils/functional.py", line 33, in __get__
>     res = instance.__dict__[self.name] = self.func(instance)
>   File "lib/django/core/urlresolvers.py", line 410, in urlconf_module
>     return import_module(self.urlconf_name)
>   File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
>     __import__(name)
>   File "/Users/briva/Desktop/owls_global/owls_core/core/urls.py", line 26, in <module>
>     url(r'^rest-auth/', include('rest_auth.urls')),
>   File "lib/django/conf/urls/__init__.py", line 52, in include
>     urlconf_module = import_module(urlconf_module)
>   File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
>     __import__(name)
>   File "lib/rest_auth/urls.py", line 3, in <module>
>     from rest_auth.views import (Login, Logout, UserDetails, PasswordChange,
>   File "lib/rest_auth/views.py", line 12, in <module>
>     from .app_settings import (TokenSerializer, UserDetailsSerializer,
>   File "lib/rest_auth/app_settings.py", line 10, in <module>
>     from .utils import import_callable
>   File "lib/rest_auth/utils.py", line 2, in <module>
>     from django.utils.importlib import import_module
> ImportError: No module named importlib

Someone did view this bug ?

**Comment by mariodev** [comment]
@briva Seems like you're using an old version of DRA, upgrading to the most recent will resolve your problem.
