### ISSUE TITLE
Are multiple sessions supported

### ISSUE THREAD

**Issue by safdarzeeshan** [Tivix/django-rest-auth#257]
I am wondering if the ability to authorize multiple sessions is supported out of the box. Currently I am using token based authentication. So if a user logs in from their laptop a token is created. If he then logs in from his mobile device he gets the same token. However when he logs out from the laptop browser, that token is destroyed which causes the session on the mobile device to also be invalid.

Is there anyway to resolve this. Essentially create a token per login session rather than per login. Auth isn't something I am very experienced in so I apologize if this turns out to be an obvious answer :)

**Comment by bkovacev** [comment]
Hi @safdarzeeshan , I have stumbled upon this same question as well. Have you figured out a way to do this? :)

**Comment by Akay7** [comment]
rest_framework.authtoken support just one token per user. You can try use different token providers

**Comment by Raisins** [comment]
Due to the fact that DRF only supports one token per user. Only single sessions are allowed for now. 
https://github.com/encode/django-rest-framework/issues/601
