### ISSUE TITLE
Custom User Model with JWT

### ISSUE THREAD

**Issue by CoolestNerdIII** [Tivix/django-rest-auth#259]
I am not sure if this functionality was never intended to be functional or not, but for when using a custom user model and also using jwt (REST_USE_JWT), even if you define the custom user details serializer, when attempting to do get the token, it blow up because it defaults to using the built in User Serializer. I got around the issue by defining my own JWT serializer, so this could serve as a note to someone in the future, or maybe it is actually an issue. Sorry for the circular logic

**Comment by morgante** [comment]
I ran into this same issue. :(

**Comment by smpte11** [comment]
I ran into the same problem. Your solution was also reference here @GetBlimp/django-rest-framework-jwt#250.

That said, djf-jwt as a special method to handle serializing the response which is aptly called "jwt_response_payload_handler" which can be overriden in django-rest-framework-jwt's settings (see their doc for that).

With that in mind, here what I did.

```
# In custom_jwt.py (or it could be directly in your serializers.py is you want)

def jwt_response_payload_handler(token, user=None, request=None):
    """ Custom response payload handler.

    This function controlls the custom payload after login or token refresh. This data is returned through the web API.
    """

    # Here you can use other serializers or custom logic, it's up to you!

    return {
        'token': token,
        'user': {

            # use user instance as you wish
            'email': user.email,
            'username': user.username,
            'first_name': user.first_name,
            'last_name': user.last_name,
            
            # add more stuff here, even relations, it's all there for the taking!
        }
    }


# In your views

from rest_auth.views import LoginView as RestAuthLoginView

class LoginView(RestAuthLoginView):
    """
    Overriden LoginView
    
    get_response serializes the response according to the default serializer (as you already know)
    which in turn, uses the default UserDetailsSeriazlizer (which we don't want)
    
    What we can do is use our custom jwt_response_payload_handler as our serializer and return in directly
    in the response
    """
    def get_response(self):
        serializers_class = self.get_response_serializer()

        if getattr(settings, 'REST_USE_JWT', False):
            
            # Use jwt_response_payload_handler since we already have the token, user (optional) and the request (optional)
            data = jwt_response_payload_handler(self.token, self.user, self.request)

            return Response(data, status=status.HTTP_200_OK)
        else:
            serializer = serializers_class(instance=self.token, context={'resquest': self.request})

            return Response(serializer.data, status=status.HTTP_200_OK)


# In our urls.py

from your_views.views import LoginView

# custom auth (make sure it's before other rest-auth urls)
    url(r'rest-auth/login', LoginView.as_view(), name='rest_login'),

```

It's not the most elegant way and certainly not the least DRY, but it works for me. 

The thing is, this method is in drf-jwt's settings as "JWT_RESPONSE_PAYLOAD_HANDLER", which is overridable. I wonder why django-rest-auth doesn't use it directly.

Maybe @mariodev, @mateusz-sikora or anyone could look into that?

If I have some time, I could even do a PR or update the doc to document this approach! :)

**Comment by maxim-kht** [comment]
Resolved in latest version
