### ISSUE TITLE
Vague documentation on social authentication

### ISSUE THREAD

**Issue by TeoTN** [Tivix/django-rest-auth#263]
However `django-rest-auth` seems to be a perfect solution for REST authentication it lacks a good documentation. Provided that I want to create a single page application on one server and REST API on another one, both authenticated only with Google, I have no clue where to start my work in terms of authorizing users. 
[Here](http://django-rest-auth.readthedocs.io/en/latest/installation.html#social-authentication-optional) I found an information that I should create a custom view inheriting from `SocialLoginView` although there's no direct information on how to use it. And [here](http://django-rest-auth.readthedocs.io/en/latest/api_endpoints.html#social-media-authentication) it's mentioned how to authenticate with Facebook but I miss information on how to get the `code` - I know it's passed as a parameter to GET request to callback URL, but then during allauth processing it is consumed and I don't know where to get it, and what should be the overall flow of application.
Could you please elaborate on that?

**Comment by apurvtwr** [comment]
I am facing this same issue. Any luck  so far ?

**Comment by apurvtwr** [comment]
Found the solution here https://github.com/Tivix/django-rest-auth/issues/203

**Comment by maxim-kht** [comment]
Added some info here https://github.com/Tivix/django-rest-auth/issues/296

Also, this Stackoverflow answer https://stackoverflow.com/questions/48319113/where-i-can-take-access-token-and-token-secret-for-twitter/48325365#48325365
