### ISSUE TITLE
Account confirm email

### ISSUE THREAD

**Issue by anrw** [Tivix/django-rest-auth#264]
Hi all,

Is there a way to implement email verification directly inside `account_confirm_email` view without any additional steps?

Currently, if I understand correctly, this view assumes you grab the key and send it to `/verify-email/` endpoint or show `ConfirmEmailView` that require from user another click.

**Comment by Vektrat** [comment]
Hello anrw,

Try if you can achieve what you are trying with this allauth setting:

```
ACCOUNT_CONFIRM_EMAIL_ON_GET = True
```

**Comment by mariodev** [comment]
@anrw Did @Vektrat answer helped?

**Comment by anrw** [comment]
Yes, @mariodev, it helped.

Thanks @Vektrat!
