### ISSUE TITLE
Receiving 'key' after social authentication 

### ISSUE THREAD

**Issue by khaled-s** [Tivix/django-rest-auth#272]
Hello
I'm implementing social authentication in my app "google" and "facebook"
after sending the "authorization code" to the server posting it to "/rest-auth/proider-name/"
I'm getting a "key"
How can I use it ?
and why I'm not receiving user data ?

**Comment by smpte11** [comment]
The key you're receiving is your API Key generated by your Django app. This is the key you use to make authenticated requests to protected ressources. Unless you're using JWT token which contains user info in it, you're not supposed to have the user infos in your response after login.

What you have to do is make a request to the user details ressource _using_ your newly received API key.

That said, if you don't mind the extra hassle, I would suggest to use their JWT config as they have extra flexibility and they enable you to pass user info with them. I wrote a reply (#259) on this issue explaining how to customize the infos you send back with the token.

Hope this helps.
