### ISSUE TITLE
Documenting response received on accessing API endpoints

### ISSUE THREAD

**Issue by pramttl** [Tivix/django-rest-auth#280]
The documentation here, http://django-rest-auth.readthedocs.io/en/latest/api_endpoints.html
only shows what input parameters each API endpoint accepts. 

However, the response of these endpoints is not documented and the user is expected to access the endpoints and explore. It would be really helpful to document the response received when these API endpoints are used.

**Comment by Akay7** [comment]
Can you show example of response. And you plans about using that doc? How it can be useful for you?

**Comment by maxim-kht** [comment]
Most auth endpoints only return status messages. I added the response values for the endpoints that return more data https://github.com/Tivix/django-rest-auth/issues/280. Also, there's additional information in docstrings https://github.com/Tivix/django-rest-auth/blob/master/rest_auth/views.py.
