### ISSUE TITLE
Using django-rest-framework-json-api with Rest Auth

### ISSUE THREAD

**Issue by jranand** [Tivix/django-rest-auth#282]
Presently I am working on a app which uses  Emberjs/Django-Rest-Framework. 
I need Django Rest Auth for Authentication and User Registration. But Ember Model only supports  JSON API spec. Kindly let me know how can I use it or extend the api view set.

**Comment by maxim-kht** [comment]
Hi @jranand, both django-rest-framework and django-rest-auth are using JSON format for displaying and accepting data. You can find more information on the provided endpoints in django-rest-auth docs: http://django-rest-auth.readthedocs.io/en/latest/api_endpoints.html. You can also see examples in the demo project: http://django-rest-auth.readthedocs.io/en/latest/demo.html.
