### ISSUE TITLE
perform extra actions after user signin

### ISSUE THREAD

**Issue by veris-neerajdhiman** [Tivix/django-rest-auth#287]
I am implementing `Google` provider. Everything is working fine. But I need to perform extra tasks as soon as a user social account is created or after user signs in. 

In `all-auth` you have `DefaultSocialAccountAdapter` where you can apply a hook. 

Do `rest-auth` provide any such kind of hook ? I didn't found any your docs.

**Comment by Akay7** [comment]
Try to use signals from allauth allauth.account.signals.user_signed_up(request, user).
docs http://django-allauth.readthedocs.io/en/latest/signals.html

**Comment by veris-neerajdhiman** [comment]
User `signUp` and `Social account Add` both are different tasks I guess (It may be possible if ) . So I need to perform an action when `Social account` is created.
I tried to use `social_account_added` signal but that doesn't even gets initiated (however somewhere is read that one condition for this signal) So I decided not to use that but use `all-auth` adapters for this and that worked for me.
