### ISSUE TITLE
Don't understand how social login is supposed to work

### ISSUE THREAD

**Issue by velis74** [Tivix/django-rest-auth#296]
The views require token & secret fields. However, to my understanding, those are obtained by actually triggering the respective service's social login procedure and are returned via a callback page.

However, how can I provide a callback URL on a client device in order to obtain the token & secret values?

I'm sure I'm missing something here.
What I expected:
Call rest-auth/facebook API which triggers the appropriate social login action on the server. To the client an URL is returned (if necessary) telling the client what URL to render in order to successfully login.
Client renders the URL which already contains the allauth callback URL to the server. When that URL is called, user is logged in and rest-auth/facebook now returns a valid session id or token.

So what is rest-auth's expected method of obtaining the token & secret values?

**Comment by maxim-kht** [comment]
The social accounts functionality is implemented using [django-allauth](https://github.com/pennersr/django-allauth/) adapters. 

Obtaining token and secret values as well as providing URL depends on exact Provider. Here's list of supported providers in django-allauth: http://django-allauth.readthedocs.io/en/latest/providers.html.

Here's for example required setup to obtain token and secret values for Twitter: https://stackoverflow.com/questions/48319113/where-i-can-take-access-token-and-token-secret-for-twitter/48325365#48325365
