### ISSUE TITLE
password reset field error

### ISSUE THREAD

**Issue by mohammad-ghanbari** [Tivix/django-rest-auth#297]
Hi,

When I send a password reset request to the backend, I get the following error:

FieldError at /rest-auth/password/reset/
Cannot resolve keyword 'is_active' into field. Choices are: auth_token, created_at, email, emailaddress, first_name, id, is_admin, last_login, last_name, logentry, password, purchaseorder, salesorder, tagline, updated_at, username

any hint how to resolve this issue is highly appreciated.

Thanks,
Mohamad

**Comment by maxim-kht** [comment]
Hi @mohammad-ghanbari Which user model are you using? Also could you please provide the whole stack trace so we could see on which line did it fail?

**Comment by mohammad-ghanbari** [comment]
Hi,

I'm extending the user model, I thought maybe this is causing the problem, but couldn't figure it out. this is my user model:

class Account(AbstractBaseUser):
    email = models.EmailField(unique=True)
    username = models.CharField(max_length=40, unique=True)
    
    first_name = models.CharField(max_length=40, blank=True)
    last_name = models.CharField(max_length=40, blank=True)
    tagline = models.CharField(max_length=140, blank=True)

    is_admin = models.BooleanField(default=False)
    
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    objects = AccountManager()
    
    USERNAME_FIELD =  'email'
    REQUIRED_FIELDS = ['username']
    
    def __unicode__(self):
        return self.email
    
    def get_full_name(self):
        return ''.join([self.first_name, self.last_name])
    
    def get_short_name(self):
        return self.first_name
    
    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True
    
    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin

This is the trace back:

Traceback:
File "/home/mohamad/Envs/ERP/local/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
  132.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/home/mohamad/Envs/ERP/local/lib/python2.7/site-packages/django/views/decorators/csrf.py" in wrapped_view
  58.         return view_func(*args, **kwargs)
File "/home/mohamad/Envs/ERP/local/lib/python2.7/site-packages/django/views/generic/base.py" in view
  71.             return self.dispatch(request, *args, **kwargs)
File "/home/mohamad/Envs/ERP/local/lib/python2.7/site-packages/rest_framework/views.py" in dispatch
  477.             response = self.handle_exception(exc)
File "/home/mohamad/Envs/ERP/local/lib/python2.7/site-packages/rest_framework/views.py" in handle_exception
  437.             self.raise_uncaught_exception(exc)
File "/home/mohamad/Envs/ERP/local/lib/python2.7/site-packages/rest_framework/views.py" in raise_uncaught_exception
  448.         raise exc

Exception Type: FieldError at /rest-auth/password/reset/
Exception Value: Cannot resolve keyword 'is_active' into field. Choices are: auth_token, created_at, email, emailaddress, first_name, id, is_admin, last_login, last_name, logentry, password, purchaseorder, salesorder, tagline, updated_at, username
Request information:
GET: No GET data

POST: No POST data

FILES: No FILES data


Thanks

**Comment by artemdumanov** [comment]
@mohammad-ghanbari Did you solve this problem?

**Comment by nerixim** [comment]
In my case the following addition to the model inheriting AbstractBaseUser worked.
I wonder if this is a Django issue.
```python
class MyBaseUser(AbstractBaseUser):
    is_active = models.BooleanField(default=False)
```

**Comment by maxim-kht** [comment]
Password reset functionality as well as some other app endpoints, etc. requires `is_active` attribute on the user. If you are using custom User model with no Django built-in attributes, adding `is_active` attribute to your User model is probably the best solution.

**Comment by arvindamirtaa** [comment]
Just out of curiosity, shouldn't something like 
`
@property
def is_active(self):
    return self.active`

work for this purpose? 

I tried it and it doesn't work.

**Comment by maxim-kht** [comment]
No, since it performs queryset filtering. It needs to be added as model attribute.

**Comment by Marsh-sudo** [comment]
What if am not using in built ```User``` django model.....i tried adding is_active but someone can't login to the application if created my own USER model
