### ISSUE TITLE
400 error when logging in when using email only mode.

### ISSUE THREAD

**Issue by genomics-geek** [Tivix/django-rest-auth#298]
I am trying to set up authentication using django-rest-auth and django-allauth. The user exists in the database and I can login to the django admin site. When I try to login using the rest-auth/login/ endpoint posting email/password, I receive a 400 error with the following response:

```
{
    "non_field_errors": [
        "Unable to log in with provided credentials."
    ]
}
```

I followed the instructions here: http://django-allauth.readthedocs.io/en/latest/configuration.html#configuration

In my settings file I have the following:

```
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_AUTHENTICATION_METHOD = 'email' 
```

If I comment out the three lines above and use the same endpoint but add the username it works. It seems to only not work with email only mode.

Thanks for your help!

**Comment by genomics-geek** [comment]
I left out AUTHENTICATION_BACKENDS in settings.  That was the issue.

**Comment by SpeciesDecipit** [comment]
> AUTHENTICATION_BACKENDS

Oh my. @genomics-geek thank you very much, I have spent about 1.5 hours to try to fix this problem. I do not think that moving from JWT to Bearer Token will so long in the new project. Thank you again.

**Comment by genomics-geek** [comment]
@SpeciesDecipit - yea it took me a long time to figure it out too haha, that is why I posted it here just in case it helped anyone else in the future

**Comment by dan-klasson** [comment]
Adding `AUTHENTICATION_BACKENDS` doesn't work for me. Using `0.9.2`.

**Comment by gitumarkk** [comment]
> I left out AUTHENTICATION_BACKENDS in settings. That was the issue.

To be more specific, I needed to add the following to `settings.py`.

```
AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
)
```

Unfortunately this is not well documented.
