### ISSUE TITLE
How to create new UserProfile automatically when a user is created?

### ISSUE THREAD

**Issue by Jakobovski** [Tivix/django-rest-auth#301]
I am wondering how to create new UserProfile automatically when a new user is created?

I tried adding a `create()` method to a custom user serializer class, (hinted at in FAQ) but the `create` method is not being called.

I also tried using a custom `all-auth` signup form, but unfortunately the `signup()` method is not being called when a new user is created from django-rest-auth.

See: http://stackoverflow.com/questions/12303478/how-to-customize-user-profile-when-using-django-allauth

Thanks

**Comment by MBuffenoir** [comment]
I would recommend using a post_save signal on your User model.
