### ISSUE TITLE
JWT Support - Documentation Clarity

### ISSUE THREAD

**Issue by stantond** [Tivix/django-rest-auth#302]
The documentation states that `django-rest-framework-jwt` needs to be installed for JWT support. Does this mean `django-rest-auth` takes care of the settings, or does `django-rest-framework-jwt` also need to be set up as per the `django-rest-framework-jwt` documentation, and if so to what extent?

**Comment by darth-cheney** [comment]
I too have not been able to get JWT to work according to the instructions (CSRF missing error on login). I have tried both the `django-rest-framework-jwt` setup instructions in concert with `django-rest-auth`, and the vanilla `django-rest-auth` instructions as written. Nada.

**Comment by verkaufer** [comment]
Hi @darth-cheney! I don't think that CSRF issue is a problem with how we integrate the `django-rest-framework-jwt` package. Could you elaborate or make a new ticket explaining your issue?

**Comment by maxim-kht** [comment]
@stantond @darth-cheney We added some more information regarding JWT support in the installation section http://django-rest-auth.readthedocs.io/en/latest/installation.html#jwt-support-optional
Please let us know if you need more info.
