### ISSUE TITLE
ImportError: cannot import name 'PasswordResetSerializer' (circular import)

### ISSUE THREAD

**Issue by simion** [Tivix/django-rest-auth#309]
Because of this commit: https://github.com/Tivix/django-rest-auth/commit/dd6db3563f9205e4a42d171f25948cc110e13b8b I cannot import and extend any serializer. 

In my project, i extend `PasswordResetSerializer` to override`get_email_options`. 
Now, a circular import is created because of that commit.

**Comment by Gagaro** [comment]
I ha ve the same issue. I have a custom `USER_DETAILS_SERIALIZER` and I extend `PasswordResetSerializer`. This results in a circular import.

**Comment by simion** [comment]
The workaround is to copy the serializer from code (it's very simple anyway), and swite your custom code on it.
This way, you don't extend the one from core, and you don't have circular import.

Here's the  core one, place your custom code on it:
https://github.com/Tivix/django-rest-auth/blob/master/rest_auth/serializers.py#L149-L179

**Comment by Gagaro** [comment]
Thanks but I prefer using the 0.8.2 version, which doesn't have the bug. I don't like copy/pasting classes directly, it's not really better than monkey patching.

**Comment by simion** [comment]
Indeed. I needed the update because it works with `django-rest-swagger`.

**Comment by maxim-kht** [comment]
Fixed in latest version.
