### ISSUE TITLE
locale directory skipped with pip install 

### ISSUE THREAD

**Issue by 1-bit** [Tivix/django-rest-auth#317]
Hi, all.

Latest version of package is installed without translations directory (locale) using pip.

**Comment by Cahersan** [comment]
I found the same issue. Maybe it has to do something with MANIFEST file?

**Comment by Cahersan** [comment]
I've checked MANIFEST.in and made a modification that may solve the issue. Please check the following pull request:
https://github.com/Tivix/django-rest-auth/pull/335

**Comment by maxim-kht** [comment]
Locale folder is included in the newest version, thanks @Cahersan !
