### ISSUE TITLE
Support for Google Captcha code

### ISSUE THREAD

**Issue by icecoldfire** [Tivix/django-rest-auth#333]
It is possible to add Google Recaptcha validation by adding these code in the RegisterSerializer class:

    import requests
    class RegisterSerializer(serializers.Serializer):
         captcha_token = serializers.CharField(required=True, write_only=True)
    
        def validate_captcha_token(self, value):
            try:
                r = requests.post(
                    'https://www.google.com/recaptcha/api/siteverify',
                    {
                        'secret': settings.RECAPTCHA_PRIVATE_KEY,
                        'response': value
                    },
                    timeout=5
                )
                r.raise_for_status()
            except requests.RequestException as e:
                raise ValidationError(
                    _('Connection to reCaptcha server failed')
                )
    
            json_response = r.json()
    
            if bool(json_response['success']):
                return value
            else:
                if 'error-codes' in json_response:
                    if 'missing-input-secret' in json_response['error-codes'] or \
                                    'invalid-input-secret' in json_response['error-codes']:
                        raise serializers.ValidationError(
                            _('Connection to reCaptcha server failed')
                        )
                    else:
                        raise serializers.ValidationError(
                            _('reCaptcha invalid or expired, try again')
                        )
                else:
                    raise serializers.ValidationError(
                        _('reCaptcha response from Google not valid, try again')
                    )

The code comes from [here](https://github.com/kbytesys/django-recaptcha2/blob/master/snowpenguin/django/recaptcha2/fields.py)

In settings.py add:

    RECAPTCHA_PRIVATE_KEY = ''

**Comment by Akay7** [comment]
I though more better keep this project simple as possible, anyway you can write your own serializer with captcha validation and override default serializer settings in settings.py.

**Comment by mariodev** [comment]
@icecoldfire Not needed as a core functionality (as pointed out by @Akay7) But thanks for sharing the snippet. May be useful to other folks. 👍
