### ISSUE TITLE
User authentication with mobile browser doesn't work after upgrade

### ISSUE THREAD

**Issue by stefko18** [Tivix/django-rest-auth#339]
I recently upgraded my Django to 1.11.2, my rest-framework to 3.6.3 and the rest-auth to 0.6 it worked fine until I checked out the mobile version via Chrome. The logged in user is always Anonymous, i don't know why. Don't understand what happend. Before (on Django 1.8 and rest on 3.3 and auth on 0.5) it worked fine everywhere, the settings remained unchanged:

REST_SESSION_LOGIN = False

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        #'rest_framework_expiring_authtoken.authentication.ExpiringTokenAuthentication',
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_THROTTLE_CLASSES': (
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ),
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/day',
        'user': '1000/day'
    }
}
This is in my installed apps:

INSTALLED_APPS = (
'django.contrib.admin',
'django.contrib.auth',
'django.contrib.contenttypes',
'django.contrib.sessions',
'django.contrib.messages',
'django.contrib.staticfiles',
'django.contrib.sites',
'django.contrib.flatpages',

'rest_framework',
'rest_framework.authtoken',
'rest_auth',
'drf_braces',
'sekizai',
'allauth',
'allauth.account',
'allauth.socialaccount',
'allauth.socialaccount.providers.facebook',
'allauth.socialaccount.providers.google',
'allauth.socialaccount.providers.linkedin_oauth2',
'rest_auth.registration',
'corsheaders'
)
What is really weird is that Django itself authenticates the user, just the ApiView doesn't, so I can not send information about the user to components in browser.

After some two hours on this issue, it seems to be some mobile/browser/APIView  issue don't know what ... desktop users are authenticated by the APIView without problems. Issue persists on mobile Firefox.

Any ideas why this happens? Thanks in advance!

**Comment by maxim-kht** [comment]
Hi @stefko18,
>I recently upgraded my Django to 1.11.2, my rest-framework to 3.6.3 and the rest-auth to 0.6

Could you please try it with latest rest-auth (version 0.9.1, https://pypi.python.org/pypi/django-rest-auth/0.9.1) ? Please let us know if the issue still persists.
