### ISSUE TITLE
Pass request in context to `LoginSerializer` in `LoginView`

### ISSUE THREAD

**Issue by bIgBV** [Tivix/django-rest-auth#340]
In Django 1.11, support for passing the `request` object to a custom authentication backend was added. When using a custom `LoginSerializer` one might use a custom backend too. django-rest-auth currently doesn't pass the request to the serializer from the `LoginView` from where it could be passed to the custom authentication backend via a `validate` method.

The change is pretty small, from the following:

    self.serializer = self.get_serializer(data=self.request.data)

to

    self.serializer = self.get_serializer(data=self.request.data, context={'request': request})

I have already made the changes to the local version of the library I have. I can submit a PR with the change. Is there anywhere I can look for the contributing guidelines so that I don't miss anything?

Thanks.

**Comment by bIgBV** [comment]
Since the PR ( #341 ) was merged, I'm closing this issue.

**Comment by nuschk** [comment]
@bIgBV : Is there a reason we don't just pass the request to authenticate() in the default serializers? This is useful when implementing custom backends (and, in our case, having throttling logic on the login_failed event), while using the default serializers.
