### ISSUE TITLE
Send real email

### ISSUE THREAD

**Issue by vince015** [Tivix/django-rest-auth#350]
Hi! Is it possible to send an actual e-mail (on sign-up and reset password)? If so how to change the e-mail body?

**Comment by mariodev** [comment]
Please refer to [django-allauth docs](http://django-allauth.readthedocs.io/en/latest/templates.html) on how to override templates.
As for sending "real" e-mails - it is not a question related to DRA. Maybe try asking this question on [stackoverflow](https://stackoverflow.com/) or just google around..
