### ISSUE TITLE
auto login user while registering second time

### ISSUE THREAD

**Issue by karthikrajender** [Tivix/django-rest-auth#352]
Hi All,

I want to generate the key token for already exist user, when he register for second time with same username and email id , i am using custom adapter but in save_user () i got struck it checks for duplicate username or email id, but that also i made a condition to avoid that problem but with out using save function, ValueError: save() prohibited to prevent data loss due to unsaved related object 'user'.
kindly help me how can i generate auth token or login

**Comment by verkaufer** [comment]
Thanks for opening an issue!

It would be [safer](https://security.stackexchange.com/a/81400), and reduce a lot of code overlap, if instead you redirect the user to your login page if the duplicate email/username exception is raised. To keep things simple, the registration form should only be used to _create_ users; the login form should only _authenticate_ existing users. 

When validating the submitted email, the application should redirect the user to the login page and prompt him/her to log in. Django-rest-auth already raises a `ValidationError` exception if this occurs.

(an aside: _Definitely_ do not allow the registration form to overwrite an existing username/email's associated password! Then anyone could authenticate themselves as another user!)
