### ISSUE TITLE
502 Bad Gateway nginx/1.13.1 during registration via facebook

### ISSUE THREAD

**Issue by Przemek625** [Tivix/django-rest-auth#353]
Localy everything seems to work fine but in production server registration via faceebok results with 502 Bad Gateway. Do you know what might be the problem?

**Comment by SerhiyRomanov** [comment]
I think, you should check nginx log's and (or) logs of our WSGI server or supervisor and post them here.

**Comment by maxim-kht** [comment]
The problem is related to the server access and not application code.
