### ISSUE TITLE
Custom Serializer Problem

### ISSUE THREAD

**Issue by deepak1725** [Tivix/django-rest-auth#354]
I am using custom Registration serializer, here it is:
#settings.py
`REST_AUTH_REGISTER_SERIALIZERS = {
    'REGISTER_SERIALIZER': 'api.serializers.MyRegisterSerializer'
}`

#serializers.py

```
class MyRegisterSerializer(RegisterSerializer):
    first_name = serializers.CharField()
    last_name = serializers.CharField()
    password = serializers.CharField(write_only=True)
    password1 = password2 = password
    
    def validate(self, data):
        return data

    def get_cleaned_data(self):
        super(MyRegisterSerializer, self).get_cleaned_data()
        return {
            'username': self.validated_data.get('username', ''),
            'password': self.validated_data.get('password', ''),
            'email': self.validated_data.get('email', ''),
            'first_name': self.validated_data.get('first_name', ''),
            'last_name': self.validated_data.get('last_name', '')
        }

```

Issue is : i am getting an unknown `!` prepended to my password, hence forth my password is unrecogonized during login.

With using MYREGISTERSERIALIZER : 
password = !HnBxoehpig...

without using MYREGISTERSERIALIZER:
password = pbkdf2_sha256...
i know password depends on many factors (SALT, Datetime and so),, but my presumption is may this is the issue that causing me login problems as all the signups done with custom serializer has this `!` prepended.

Kindly check the root cause.

**Comment by Raisins** [comment]
From https://github.com/Tivix/django-rest-auth/blob/master/docs/configuration.rst
```
Note

The custom REGISTER_SERIALIZER must define a def save(self, request) method that returns a user model instance
```
this might not be the root cause of your `!` issue but you are missing the save which might cause unexpected results.

**Comment by deepak1725** [comment]
I am extending in-built rest-auth's Register Serializer... why i need to rewrite the same code..?? 
this goes over my mind...

**Comment by mariodev** [comment]
@deepak1725 
Ref: https://github.com/pennersr/django-allauth/blob/ff44f32187b996d7920475a7204c2291fd692e77/allauth/account/adapter.py#L238

Registration logic is deeply dependent on  `django-allauth` and it requires `password1` field inside validated data, otherwise (as you see by looking at the code) it will set unusable password (hence the `!` prefix)

So your options are:

- either use default password field names as intended by build-in adapter (`password1`, `password2`).
- if you insist on using your own custom password field names, you then need to completely override `save` method and handle the whole registration logic by yourself..

**Comment by deepak1725** [comment]
@mariodev  That makes sense!! Thank you for knowledge!!

**Comment by deepak1725** [comment]
@shakeelcse09 
```
from rest_auth.registration.serializers import RegisterSerializer

class MyRegisterSerializer(RegisterSerializer):
    first_name = serializers.CharField()
    last_name = serializers.CharField()

    def get_cleaned_data(self):
        super(MyRegisterSerializer, self).get_cleaned_data()
        return {
            'username': self.validated_data.get('username', ''),
            'password1': self.validated_data.get('password1', ''),
            'email': self.validated_data.get('email', ''),
            'first_name': self.validated_data.get('first_name', ''),
            'last_name': self.validated_data.get('last_name', '')
        }
```
For Detailed Code, here it is https://github.com/deepak1725/djangular/blob/master/api/serializers.py

**Comment by shakeelcse09** [comment]
@deepak1725  thanks a lot. it helped.

**Comment by deven769** [comment]
thank you deepak1725 it worked.
