### ISSUE TITLE
Invalid grant error

### ISSUE THREAD

**Issue by pkyalo** [Tivix/django-rest-auth#360]
Am always getting **Error retrieving access token: b'{\n  "error" : "invalid_grant"\n}**'
 when using google auth id_token. Access_token works fine though

**Comment by murdav** [comment]
@pkyalo did you solve it?
Could you copy here your settings, views and the cURL command ?

**Comment by pkyalo** [comment]
Yes, I solved it. The problem was that I was exchanging the Authorization code using a wrong method so this wasn't  a problem of the package but a user problem. 

Thanks @murdav
