### ISSUE TITLE
Bug: code assumes email is unique

### ISSUE THREAD

**Issue by adamdonahue** [Tivix/django-rest-auth#365]
During login, this code fails if more than one user has the same email:

`rest_auth/serializers.py in validate`:

![image](https://user-images.githubusercontent.com/2406542/31032728-384f0e38-a52b-11e7-9004-509b3b93c248.png)

Django allows for multiple users to leverage the same email address.

**Comment by maxim-kht** [comment]
Hi @adamdonahue this code is only executed if email and not username is used in order to authenticate - if email is used for authentication it needs to be unique per user.

**Comment by adamdonahue** [comment]
Still feels like a bug in that a more appropriate exception could be
raised. I can add one.
