### ISSUE TITLE
Field name `username` is not valid for model `User`.

### ISSUE THREAD

**Issue by igsm** [Tivix/django-rest-auth#368]
I use custom user model. I thought that by defining the following settings it will ignore 'username'. However, I still hit the same error.

Field name `username` is not valid for model `User`.
_~/lib/python3.6/site-packages/rest_framework/serializers.py in build_unknown_field, line 1258_

```
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_UNIQUE_EMAIL = True
REST_USE_JWT = True
JWT_SERIALIZER = True
REST_USE_JWT=True
```

I am going nuts implementing this stuff. What am I missing? Lets assume that email is verified, I'd like to login and get JWT in the response. Do I need to implement custom LoginSerializer? But, then if you look at how it is [configured by default](https://github.com/Tivix/django-rest-auth/blob/master/rest_auth/serializers.py), you can see that it has some logic that checks what kind of credentials have been used on login attempt. I am lost.

**Comment by Dineshs91** [comment]
You have to override `UserDetailsSerializer` to remove `username` from the `fields` option. Hopefully this should solve the problem.

**Comment by maxim-kht** [comment]
It is correct - when using custom user model that does not have one of Django built-in attributes like `username`, `email`, `first_name`, `last_name`, etc. you need to define custom `UserDetailsSerializer`
