### ISSUE TITLE
Demo exceptions

### ISSUE THREAD

**Issue by FZambia** [Tivix/django-rest-auth#38]
Hello! Just made a fresh install from master branch and came across several exceptions:

http://localhost:8000/email-verification/

```
NoReverseMatch at /email-verification/
Reverse for 'verify_email' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
Request Method: GET
Request URL:    http://localhost:8000/email-verification/
Django Version: 1.7.1
Exception Type: NoReverseMatch
Exception Value:    
Reverse for 'verify_email' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
```

Also during sign up process:

```
NoReverseMatch at /rest-auth/registration/
Reverse for 'account_email_verification_sent' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
```

**Comment by Sshuichi** [comment]
I'm still facing this issue 
My config for allauth : 
`ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
ACCOUNT_USERNAME_REQUIRED = True
ACCOUNT_AUTHENTICATION_METHOD = 'username_email'`
