### ISSUE TITLE
PasswordReset template doesn't exist

### ISSUE THREAD

**Issue by mbaragiola** [Tivix/django-rest-auth#381]
Hello, `restauth:rest_password_change` is trying to use template `registration/password_reset_email.html` but fails to find it. I haven't find such template neither in `django-allauth` nor `django-rest-auth` when looking myself.

Any heads up?

**Comment by mbaragiola** [comment]
Had to rewrite `PasswordResetSerializer` and `PasswordResetConfirmSerializer` in order to skip using `django` and/or `django-allauth` forms and templates. Won't close the issue since I consider this should solved.

**Comment by mariodev** [comment]
No need to override serializers, just add your file in the project-level template path.
