### ISSUE TITLE
Can't override "password_reset_key_message.txt"

### ISSUE THREAD

**Issue by MadReal** [Tivix/django-rest-auth#393]
I'm having issues overriding the default email for the "forgot password". I can override the 2 email for "email confirmation" without any issue but not with this one.

Not matter the extension, the one sent is always the default one that comes with the package.

Thanks

**Comment by iMerica** [comment]
Issue persists for me too. Were you able to find a fix @MadReal ?

**Comment by Koomook** [comment]
Same issue here. Any suggestions? @MadReal @iMerica

**Comment by rpkilby** [comment]
[`password_reset_key_message.txt`](https://github.com/pennersr/django-allauth/blob/master/allauth/templates/account/email/password_reset_key_message.txt) is a template provided by allauth. You'd need to override that path.

**Comment by anuj9196** [comment]
The email sent is not using `password_reset_key_message.txt`, instead it is sending Django's default email template from `sites-packages/django/contrib/admin/templates/registration/password_reset_email.html`

Can anyone make clear about this?

**Comment by anuj9196** [comment]
For those whos are facing issue, I managed to get it work by overriding Django's template.

Create a new file at `templates/registration/password_reset_email.html` with content

```
{% load i18n %}{% blocktrans with site_name=current_site.name site_domain=current_site.domain %}Hello from {{ site_name }}!

You're receiving this e-mail because you or someone else has requested a password for your user account.
It can be safely ignored if you did not request a password reset. Click the link below to reset your password.{% endblocktrans %}

{% block reset_link %}
{{protocol}}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}
{% endblock %}

{% blocktrans with site_name=current_site.name site_domain=current_site.domain %}Thank you for using {{ site_name }}!
{{ site_domain }}{% endblocktrans %}
```

**Comment by anuj9196** [comment]
For the developer:

In the [`PasswordResetSerializer`](https://github.com/Tivix/django-rest-auth/blob/624ad01afbc86fa15b4e652406f3bdcd01f36e00/rest_auth/serializers.py#L156)  you are using [`PasswordResetForm`](https://github.com/Tivix/django-rest-auth/blob/624ad01afbc86fa15b4e652406f3bdcd01f36e00/rest_auth/serializers.py#L3) which is provided by

`` `
from django.contrib.auth.forms import PasswordResetForm
```

In order to use the `allauth` email template, you need to use `ResetPasswordForm` provided by `allauth` instead.

**Comment by opeodedeyi** [comment]
> For those whos are facing issue, I managed to get it work by overriding Django's template.
> 
> Create a new file at `templates/registration/password_reset_email.html` with content
> 
> ```
> {% load i18n %}{% blocktrans with site_name=current_site.name site_domain=current_site.domain %}Hello from {{ site_name }}!
> 
> You're receiving this e-mail because you or someone else has requested a password for your user account.
> It can be safely ignored if you did not request a password reset. Click the link below to reset your password.{% endblocktrans %}
> 
> {% block reset_link %}
> {{protocol}}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}
> {% endblock %}
> 
> {% blocktrans with site_name=current_site.name site_domain=current_site.domain %}Thank you for using {{ site_name }}!
> {{ site_domain }}{% endblocktrans %}
> ```

hello, I tried this solution but discovered that using html elements don't work properly, it just sends a mail with raw html code. How were you able to style yours?

**Comment by opeodedeyi** [comment]
> [`password_reset_key_message.txt`](https://github.com/pennersr/django-allauth/blob/master/allauth/templates/account/email/password_reset_key_message.txt) is a template provided by allauth. You'd need to override that path.

I overrode that path, it didn't work. Please can you share how you solved this, it could save me weeks

**Comment by b0lle** [comment]
@opeodedeyi did you solve this? My password reset also sends plain text files.

**Comment by opeodedeyi** [comment]
yes, I did solve this eventually. do you also have an issue with that?
