### ISSUE TITLE
"User is already registered with this e-mail address."

### ISSUE THREAD

**Issue by EvanZ** [Tivix/django-rest-auth#409]
Trying to implement a FB login flow. I upgraded to v.0.9.3 because I thought it fixes the bug where you are already signed up via email. However, it now seems that the code knows the user is registered but doesn't sign him in anyway. I am getting the access_token just fine from FB. I have tried both the `/rest-auth/facebook/` and `/rest-auth/facebook/connect/ `endpoints, although not quite understanding the difference. At any rate, they are both resulting in the same 400 error.

**Comment by EvanZ** [comment]
I found these comments in the latest commit:

```
# We have an account already signed up in a different flow
+            # with the same email address: raise an exception.
+            # This needs to be handled in the frontend. We can not just
+            # link up the accounts due to security constraints
```

Couple questions. Why is this a security issue? Isn't the whole point of social authentication that you trust the OAuth provider? Second, how is one supposed to handle this in the frontend? It's a common occurrence that people sign up for email first (often simply because a site or app adds social login later in the development cycle). It seems to me the only option this leaves me with is to tell the user "Sorry, you can only login with your email account." Is that true?

**Comment by philippeluickx** [comment]
Hi @EvanZ ! There is a similar discussion on the django allauth package that leads to the same conclusion. The behaviour is basically replicated from that.
There is no way that social providers can guarantee that the user on their site is the same as the one on your site, even if both have the same email address. Hence security issue. Check allauth for more details on the discussion.
As for handling it on the frontend: You could ask the user to login first "the old way" and then once logged in, connect the social accounts. There's methods for that in allauth, although not sure if that's implemented in allauth already...

**Comment by maxim-kht** [comment]
Thank you @philippeluickx, yes it is implemented in the latest version by @aleksihakli and can be used via `/rest-auth/facebook/connect/` view.

@EvanZ The difference between `/rest-auth/facebook/` and `/rest-auth/facebook/connect/ ` is, connect view only works after you logged in as a regular user via email and you wish to attach social account to this existing user. Here's more info in the docs: http://django-rest-auth.readthedocs.io/en/latest/installation.html#additional-social-connect-views.

In order to use social connect view you need to
1) Login as existing user (registered before as a non-social account)
2) Access `/rest-auth/facebook/connect/` to attach social account to this existing user.

**Comment by EvanZ** [comment]
Thanks @maxim-kht. I understand now.

**Comment by aleksihakli** [comment]
As previously stated in the thread it is possible that social authentication providers do not check the validity of user credentials. 

For example, it's possible to register a Facebook account with a phone number and then set a bogus email. I'm not sure if Facebook verifies all email addresses on set. This could lead to a login getting federated from Facebook to a custom backend and someone hijacking your account. 

This is why it's important to only connect social accounts when the user connecting them is logged in to their normal account. 

We went through some different providers and scenarios in a past project and deemed that this was a legitimate problem as e.g. allauth has a whopping list of 63 supported providers. We couldn't verify that all of them legitimately check the validity of user email addresses and other information; hence automatically connecting the accounts is very problematic.

**Comment by EvanZ** [comment]
At least with FB, they tell you whether an email is verified or not. If they say it is verified, my understanding is that is a guarantee they verified it. I don't know about how other social providers do it. From my perspective, it would make more sense to enable the library users to "trust and verify" the social auth providers that they use, and not force one way of thinking, but it is not my project, so not my choice to make. I understand now the security issue, which is important, and the tradeoffs. I will continue using this library because there really aren't any good alternatives from what I've seen, and I don't want to reinvent the wheel at all. Thanks for all your efforts!

**Comment by aleksihakli** [comment]
I guess you could implement the trust settings if you're inclined. I think it's not sound security-wise to allow implicit connection of different user accounts, only explicit where both are verified and logged in. This sports more use cases as well, I think.
