### ISSUE TITLE
DRF 3 changes HttpRequest to Request

### ISSUE THREAD

**Issue by schemacs** [Tivix/django-rest-auth#43]
When I do registration, one exception raise as follow:

    add_message() argument must be an HttpRequest object, not 'Request'.

The upper level code related to django-rest-auth is at /rest_auth/registration/views.py#L27

    def form_valid(self, form):
        self.user = form.save(self.request)
        return complete_signup(self.request, self.user,
                               app_settings.EMAIL_VERIFICATION,
                               self.get_success_url()) 

And add_message in django will check request object:

    if not isinstance(request, HttpRequest):
        raise TypeError("add_message() argument must be an HttpRequest object, "
                        "not '%s'." % request.__class__.__name__) 

but [docs](http://www.django-rest-framework.org/api-guide/requests/ ) from drf says:
   
    Note that due to implementation reasons the Request class does not inherit from HttpRequest class, but instead extends the class using composition.

Related stackoverflow thread:
http://stackoverflow.com/questions/27456273/using-django-message-framework-with-rest-framework

I will make a pull request if you guys are going to support drf 3.0.

**Comment by jayakrishnandingit** [comment]
@mateusz-sikora when will this issue be fixed? I would like this to be fixed ASAP, since I do have an urgent client requirement. Moreover, if its not getting fixed soon, what are the possible work around?

**Comment by mateusz-sikora** [comment]
@jayakrishnandingit you can fork this project to your account, make fix there and use your version.
after that you can create a pull request to this project.

**Comment by mateusz-sikora** [comment]
@schemacs @jayakrishnandingit fix for this issue is in place
