### ISSUE TITLE
POST Request returns "Method \"GET\" not allowed."

### ISSUE THREAD

**Issue by realPrimoh** [Tivix/django-rest-auth#447]
Hello,

I have set up django-rest-auth as per the installation tutorial, yet I am not able to use the login API endpoint. When I send a POST request with the correct information, I receive a 405 status error in response with  "Method \"GET\" not allowed."

However, when I navigate to the actual URL and POST it from the online form, it works fine and returns a token.

Help?!

**Comment by apex-base** [comment]
how did you solve it at the server side?

**Comment by rams3sh** [comment]
Faced the same issue. 

In our case , we had enabled the APPEND_SLASH (https://docs.djangoproject.com/en/3.0/ref/settings/#append-slash) , which led to url redirection via GET Method leading to the issue. Thought I will post it here, in case anyone else faces the same issue.

**Comment by codinkage** [comment]
Faced the same issue too. 
The problem was coming for URL redirection
www.mysite.com gives me the error until I changed it to www.mysite.com/; 
This fixed the problem
