### ISSUE TITLE
Social login with VK

### ISSUE THREAD

**Issue by gorros** [Tivix/django-rest-auth#45]
Hi,

I have endpoints for social login with Facebook and VK. Facebook login works perfect. But adapter for VK is little bit different and it needs also uid to complete login. Is there way to configure SocialLoginSerializer like other serializer, so I can override it?

Thank you.

**Comment by mateusz-sikora** [comment]
Sure, you can create your own SocialLoginSerializer and define your own view class, like:

```
from rest_auth.views import Login
class CustomLogin(Login):
    serializer_class = CustomSocialLoginSerializer
    adapter_class = VKOAuth2Adapter
```

Could you paste error traceback which you get when using VK adapter?

**Comment by gorros** [comment]
I use following view:'
```
class VKLogin(SocialLogin):
    adapter_class = VKOAuth2Adapter
```
and receive following error
```
TypeError at /api/auth/vk/

string indices must be integers
```
which is result of following line in SocialLoginSerializer
```
 login = self.adapter.complete_login(request, app, token,
                                                response=access_token)
```
since complete_login in VK0Auth2Adapter is defined a little bit deferent that in Facebook0Auth2Adapter:
```
def complete_login(self, request, app, token, **kwargs):
        uid = kwargs['response']['user_id']
        resp = requests.get(self.profile_url,
                            params={'access_token': token.token,
                                    'fields': ','.join(USER_FIELDS),
                                    'user_ids': uid})
        resp.raise_for_status()
        extra_data = resp.json()['response'][0]
        return self.get_provider().sociallogin_from_response(request,
                                                             extra_data)
```

Mainly you a need also to pass user_id (kwargs['response']['user_id']) to obtain relevant response according http://vk.com/dev/users.get. And as I understand from VK API docs on this step access_token is not required.

**Comment by mateusz-sikora** [comment]
So the only solution for you at this moment is to define you own social login serializer basing on SocialLoginSerializer and override validate method. There is no way to make it simpler, unfortunately.

You can also fork this project, make a patch and create a pull request to apply it to DRA code.

**Comment by gorros** [comment]
That's exactly  what I was planing to do.

**Comment by gorros** [comment]
By the way, I am glad you fixed UserDetailsSerializer import in rest_auth/registration/views.py in v0.3.3 (https://github.com/Tivix/django-rest-auth/commit/e9fee3aa92beebfee3774aa906e7db3942c78583).

**Comment by sburavtsov** [comment]
Hi gorros, sorry I write it here, did you solve vk authorization issue? Can you help me with that?
My email is serobur@gmail.com

**Comment by gorros** [comment]
@sburavtsov This was a while ago, but according to my code this should solve the problem.
```

class CustomVKOAuth2Adapter(VKOAuth2Adapter):

    def complete_login(self, request, app, token, **kwargs):
        uid = kwargs['response']['user_id']
        resp = requests.get(self.profile_url,
                            params={'fields': ','.join(USER_FIELDS),
                                    'user_ids': uid})
        resp.raise_for_status()
        extra_data = resp.json()['response'][0]
        return self.get_provider().sociallogin_from_response(request,
                                                             extra_data)
```

**Comment by sburavtsov** [comment]
Than you! I will try it.

-------------------------------------------
With the best regards, Sergey
Skype: serobur_skype
Phone: +7 960 102 40 40

**Comment by KhasanovBI** [comment]
The problem is actual. Please reopen issue.

**Comment by SerhiyRomanov** [comment]
Are any solutions this problem? The solutions [https://github.com/Tivix/django-rest-auth/issues/45#issuecomment-181517670](url)  from **gorros** not work for me (((

**Comment by kamirt** [comment]
I had the same problem so I had to find the solvation. The point is here:
  File "/home/kamirt/nissaenv/lib/python3.4/site-packages/rest_auth/registration/serializers.py", line 247, in validate
    login = self.get_social_login(adapter, app, social_token, access_token)
  File "/home/kamirt/nissaenv/lib/python3.4/site-packages/rest_auth/registration/serializers.py", line 180, in get_social_login
    social_login = adapter.complete_login(request, app, token, response=response)

This "response" parameter in case VK must be like this: {user_id:*******, access_token: *******, expire_time: *******}. But this  function passes already parsed response (only access_code).

**Comment by MIRAMAXED** [comment]
I have the same problem too:
File ... in complete_login
  37.         uid = kwargs['response']['user_id']

Exception Type: TypeError at /api/vk/
Exception Value: string indices must be integers

What to do?

**Comment by taime** [comment]
So what is the final solution?
Here is the hole code:

`
from allauth.socialaccount.providers.vk.views import VKOAuth2Adapter

class CustomVKOAuth2Adapter(VKOAuth2Adapter):

    def complete_login(self, request, app, token, **kwargs):
        uid = kwargs['response']['user_id']
        resp = requests.get(self.profile_url,
                            params={'fields': ','.join(USER_FIELDS),
                                    'user_ids': uid})
        resp.raise_for_status()
        extra_data = resp.json()['response'][0]
        return self.get_provider().sociallogin_from_response(request,
                                                             extra_data)
`
in urlpatterns: 
`url(r'^rest-auth/vk/$', CustomVKOAuth2Adapter, name='vk_login'),`

And I get error in browser what open http://127.0.0.1:8000/rest-auth/vk/: 
`AttributeError at /rest-auth/vk/
'CustomVKOAuth2Adapter' object has no attribute 'status_code'`

How to fix it?
