### ISSUE TITLE
(Security bug) PasswordResetConfirm doesn't check token! It allows to change password for anyone

### ISSUE THREAD

**Issue by axens** [Tivix/django-rest-auth#47]
https://github.com/Tivix/django-rest-auth/blob/master/rest_auth/serializers.py#L116 

Perhaps, you forgot to raise an exception, for example like that:
<pre>
if self._errors:
            raise serializers.ValidationError(self._errors)
</pre>

**Comment by mateusz-sikora** [comment]
I think that `is_valid()` method of Serializer class will rise an exception if there are any items in `self._errors` list. I'm almost sure that it was working like that in DRFv2.4, but will check it for DRFv3.0. 

Thanks for reporting this!

**Comment by mateusz-sikora** [comment]
@axens You were right! Patch is already pushed to the repo, will release new version shortly.
Thanks once again for catching this bug!

**Comment by axens** [comment]
@mateusz-sikora Thank you!
