### ISSUE TITLE
Change User Email Endpoint

### ISSUE THREAD

**Issue by joeldhenry** [Tivix/django-rest-auth#471]
User should be able to modify email address & confirm email Change on their account. 
Such as Auth/changeEmail & Auth/confirmEmail

**Comment by gdhameeja** [comment]
I can try to take this up. However, I am new to open source, so I might need some guidance.

**Comment by PeterSR** [comment]
I too would love this feature.

**Comment by joeldhenry** [comment]
@PeterSR thanks the response, i saw this issue, but don't know about django-allauth and don't want to futher complicate my project. 

@gdhameeja a good place to start would be to look at the password reset email functionality because it should be pretty similar to the email reset.

steps should be:

1. email address is posted to email change endpoint, and marked as pending verification
2. email address should remain as the old email untill the new email address is verified
3. an email should be sent to the new email address with a token to post back to an endpoint to verify the email
4. on posting the token should verify the new email address and remove the old one from the profile.

**Comment by joeldhenry** [comment]
Update: Implemented by extending django-allauth

**Comment by ayushin** [comment]
@joeldhenry can you clarify if you have implemented it or if a developer should extend django-allauth himself?

**Comment by jamesremuscat** [comment]
There weren't any commits to `master` between @joeldhenry's two comments above, so I'm assuming it's the latter, but it would be nice to have some guidance - for example, is the method outlined in https://github.com/Tivix/django-rest-auth/issues/127#issuecomment-166889955 still relevant/optimal? Or is there a preferred way?
