### ISSUE TITLE
compatibility with django-axes

### ISSUE THREAD

**Issue by jedie** [Tivix/django-rest-auth#477]
I would like to use django-rest-auth with django-axes.

I raise into `AxesModelBackend.RequestParameterRequired` because `AxesModelBackend` needs the request object, see: https://django-axes.readthedocs.io/en/latest/configuration.html#authentication-backend-problems

The Django Rest Framework will pass it since v3.7

`rest_auth/serializers.py` doesn't do this.

**Comment by mariodev** [comment]
@jedie https://github.com/Tivix/django-rest-auth/blob/479a40d2ccd69d69f7a05d716f30239dd3ef2343/rest_auth/serializers.py#L25

Are you sure this doesn't happen in some other parts of your code?

**Comment by GabLeRoux** [comment]
I am reproducing this in a project I'm working on and I did not exactly identify why this happens. Good news is I managed to get `django-axes` to work in the demo `django-rest-auth` project:

https://github.com/Tivix/django-rest-auth/pull/555

Interesting part is here:
https://github.com/Tivix/django-rest-auth/pull/555/files#diff-f442e6771d311ff0ec61773f419e4d2e

![image](https://user-images.githubusercontent.com/1264761/60612541-dbcfe180-9d96-11e9-8cea-a45caac092a7.png)
