### ISSUE TITLE
SocialConnectView not working to connect existing/logged in user

### ISSUE THREAD

**Issue by PedroBern** [Tivix/django-rest-auth#490]
Im trying to connect social account to existing user.

**Social login works great, the problem is to connect an already registered user.**
 
as the docs:

```
#views.py

from allauth.socialaccount.providers.facebook.views import FacebookOAuth2Adapter
from rest_auth.registration.views import SocialLoginView, SocialConnectView

class FacebookLogin(SocialLoginView):
    adapter_class = FacebookOAuth2Adapter

class FacebookConnect(SocialConnectView):
    adapter_class = FacebookOAuth2Adapter
```

and

```

#urls.py

...
from .views import FacebookLogin, FacebookConnect

urlpatterns = [
    ....
    path('facebook/connect/', FacebookConnect.as_view(), name='fb_connect'),
    path('facebook/', FacebookLogin.as_view(), name='fb_login'),
    ....
]
```

on my fronend, when the user is logged in and try to connect his account to facebook:

```
axios.post('auth/v1/facebook/connect/', {
     // token is access_token from facebook response
      access_token: token,
    })
```

but the backend response is:

```
...
status: 401
statusText: "Unauthorized"
detail:"Authentication credentials were not provided."
...
```

my settings:

```
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

...

# allauth settings
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False
SOCIALACCOUNT_QUERY_EMAIL= True
```

PS: Im using react frontend with webpack

**Am I missing something that I should send to '...facebook/connect/' besides access_token ?**

**Comment by PedroBern** [comment]
I was not providing the authentication correctly, now it's ok.

**Comment by Hunter3173** [comment]
Hi, please how must I provide the authentication ? I have the same problem

**Comment by johnfidel98** [comment]
@leoandfox did you try 
headers: {
          'Content-Type': 'application/x-www-form-urlencoded',
          'Authorization': 'Token <token goes here>'
        }

**Comment by SohaibShafiq1** [comment]
> I was not providing the authentication correctly, now it's ok.

can you provide the solution

**Comment by SohaibShafiq1** [comment]
if we wants to loggin what authentication credentials we have to provide for SocialConnectView
