### ISSUE TITLE
Error 500 during registration

### ISSUE THREAD

**Issue by PinoMatranga** [Tivix/django-rest-auth#497]
Request
```
http POST http://localhost:8000/rest-auth/registration/ username="testuser" password1="examplepassword" password2="examplepassword" email="testuser@example.com"
```

Response
```
HTTP/1.1 500 Internal Server Error
Content-Length: 22351
Content-Type: text/plain; charset=utf-8
Date: Wed, 02 Jan 2019 23:29:22 GMT
Server: WSGIServer/0.2 CPython/3.6.7
Vary: Cookie
X-Frame-Options: SAMEORIGIN

ConnectionRefusedError at /rest-auth/registration/
[Errno 111] Connection refused
```

But actually the user is created, indeed if I do again the same request, I receive this response:
```
HTTP/1.1 400 Bad Request
Allow: POST, OPTIONS
Content-Length: 125
Content-Type: application/json
Date: Wed, 02 Jan 2019 23:33:18 GMT
Server: WSGIServer/0.2 CPython/3.6.7
Vary: Accept, Cookie
X-Frame-Options: SAMEORIGIN

{
    "email": [
        "A user is already registered with this e-mail address."
    ],
    "username": [
        "A user with that username already exists."
    ]
}
```

Where is the bug to fix?

**Comment by mariodev** [comment]
Probably something wrong with your email settings (assuming you have email confirmation enabled). Please read this carefully:
https://docs.djangoproject.com/en/2.1/topics/email/#console-backend

and adjust proper settings for your development environment.

Closing issue, since it's is not directly related to DRA. Please try jusing stackoverflow for any further help.

**Comment by boldrack** [comment]
> ```python
> from django.views.generic import TemplateView
> ```

Ain't fixing it.

**Comment by Angeloem** [comment]
the way to fix this thing is [https://stackoverflow.com/questions/30783472/django-rest-auth-angular-500-internal-error](here)... I had the same problem and using this guy's suggestion, everything went cool
