### ISSUE TITLE
AttributeError at /rest-auth/login/

### ISSUE THREAD

**Issue by ghost** [Tivix/django-rest-auth#5]
**Gist**: https://gist.github.com/dyzajash/7f95c631d61b511ccbf9

**Code used**: https://github.com/Tivix/angular-django-registration-auth + https://github.com/dyzajash/nemu

**Problem**: 

When I try to login I can **GET** form but I can't **POST** it. In browser it gives me "type object 'Token' has no attribute 'objects'" error, and in console.log i got **500 (INTERNAL SERVER ERROR)**

**SYSTEM**: precise32 VagrantBox

**Comment by shredding** [comment]
Should be added to the docs as well!
