### ISSUE TITLE
How to access as an authenticated user once I register the social account?

### ISSUE THREAD

**Issue by spider-hand** [Tivix/django-rest-auth#510]
Hi I could figure out how to register with Google account but I still don't understand how to use `key` which I get in exchange for `access_token`. How  can I access as an authenticated user once I register the account? 
I tried to send request with header like `Authorization: Token <key>` and `Authorization: Token <access_token>` and  some other ways but API always returns `403`.

**Comment by hemanth-sp** [comment]
hi can you share code hot integrate google sigin in
