### ISSUE TITLE
Django/Vue braces added to request method after logout

### ISSUE THREAD

**Issue by JVP3122** [Tivix/django-rest-auth#512]
Cross-post from [axios/axios#1994 (comment)](https://github.com/axios/axios/issues/1994#issuecomment-464779874) that I thought was an axios issue but a user tried it out with a mock backend server and didn't have a problem. I'm also posting on https://github.com/davesque/django-rest-framework-simplejwt/ because I'm not sure if it's a simplejwt issue or a rest-auth issue (or maybe even further down into Django/DRF)

I have a basic user management project that I'm using off of which to scaffold other projects. It is a Vue CLI 3 front end and Django/Django REST Framework/Django REST Auth back end. The project I'm posting here uses sqllite but it can relatively easily be converted to another db.

Here is the link to the full repo for anyone who is willing to download to try to replicate my issue: https://github.com/JVP3122/user-project

I'm having a very strange problem in that when I log out of the site and then try to log back in directly from the same page it seems that axios is adding the payload to the beginning of the request method.

For example, in the images found in the post I put up in Imgur (https://imgur.com/a/bEsx662) the user name is simply "test" with the password "password", and when I try to log back in after logging out the subsequent login attempt is no longer a POST route, but instead a {}POST route. If I try again, the route becomes a {"USERNAME":"TEST","PASSWORD":"PASSWORD"}POST method.

I've tried looking at the config in the axios request interceptor, looking at the dispatch method in the rest_framework source code (checking request details in the dispatch function in , and I can't figure out what is going on or how to solve this. It's a small bug that doesn't take away from the rest of the functionality, but it's a bug nonetheless.

Any help would be appreciated.

**Comment by mariodev** [comment]
I could not replicate your issue. I could log in/log out multiple time with no problem. I'm closing it, as it's not DRA or backend related. Please try posting same issue in SO instead, you will get better chance with the wider audience..

**Comment by JVP3122** [comment]
Thanks for looking into it. It's been up on SO for about two months now with no response, which is why I posted here and on DRF-simplejwt and axios, all of which say it's not an issue they've seen. I must have a ghost or something that's screwing me up and I'll just have to dig to find the ghost. Thanks again
