### ISSUE TITLE
Does django-rest-auth encrypt tokens in DB?

### ISSUE THREAD

**Issue by luisroel91** [Tivix/django-rest-auth#546]
I do not see this mentioned anywhere in the docs...

Thank you!

**Comment by rpkilby** [comment]
The default token implementation is the one provided by DRF. 

https://github.com/Tivix/django-rest-auth/blob/624ad01afbc86fa15b4e652406f3bdcd01f36e00/rest_auth/models.py#L3

If you look at those models, the token is neither hashed nor encrypted.
