### ISSUE TITLE
RegisterView does not work with custom auth token model.

### ISSUE THREAD

**Issue by sambenas** [Tivix/django-rest-auth#562]
If using a custom authentication token model, the `related_name` cannot be `auth_token` or that will clash with the default token model related name and the django project will fail to start.

The RegisterView returns an authentication token using `user.auth_token`.  Since the related name for a custom token model had to be changed, `user.auth_token` does not actually exist.

As a workaround a custom RegisterView can be subclassed with `get_response_data()` overridden, but a possible fix would be checking if a custom auth token model is used and performing a `TokenModel.objects.get(user=user)`

**Comment by rpkilby** [comment]
You likely have `'rest_framework.authtoken'` in your `INSTALLED_APPS` setting. If you're using a custom token model, it's unnecessary to use the `authtoken` app.

The installation guide should be updated to point this out.

**Comment by sambenas** [comment]
Removing `rest_framework.authtoken` from installed apps worked,  I changed the related_name on my custom token model to 'auth_token' without any Django errors.
