### ISSUE TITLE
can't use localhost:8000/rest-auth/registration/ to add new user.

### ISSUE THREAD

**Issue by ThomasGrzybowski** [Tivix/django-rest-auth#57]
Using angular-django-registration-auth from "python manage.py runserver" (not gunicorn) I am able to utilize the /login/ api url "http://localhost:8000/rest-auth/login/".  But when I attempt to use the /registration/ api url "http://localhost:8000/rest-auth/registration/", I get HTTP 405 METHOD NOT ALLOWED, and a form showing only "Content:" and a textbox.

This is a new installation.  Here is my "requirements.txt" content:

Django==1.7.6
dj-database-url==0.3.0
dj-static==0.0.6
django-appconf==1.0.1
djangorestframework==3.0.5
django-rest-auth==0.3.4
django-allauth==0.19.1
drf-nested-routers==0.9.0
drf-extensions
gunicorn==19.1.1
six==1.9.0
static3==0.5.1
wsgiref==0.1.2

I believe I have correctly followed the instructions in "http://django-rest-auth.readthedocs.org/en/latest/installation.html#registration-optional" for INSTALLED_APPS , and myapp/urls.py.  

Here are the relevant contents of myapp/settings.py:
INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'rest_auth',
    'allauth',
    'allauth.account',
    'rest_auth.registration',
)

TEMPLATE_CONTEXT_PROCESSORS = (
    # Required by allauth template tags
    "django.core.context_processors.request",
    # allauth specific context processors
    "allauth.account.context_processors.account",
    "allauth.socialaccount.context_processors.socialaccount",
)

AUTHENTICATION_BACKENDS = (
    # Needed to login by username in Django admin, regardless of `allauth`
    "django.contrib.auth.backends.ModelBackend",
    # `allauth` specific authentication methods, such as login by e-mail
    "allauth.account.auth_backends.AuthenticationBackend",
)

Thanks!

**Comment by SiddharthMantri** [comment]
Facing the same issue. What I am able to figure out is that the `/registration/` api doesn't exist in `rest_auth.urls`. Going through the docs here: http://django-rest-auth.readthedocs.org/en/latest/api_endpoints.html#registration it seems that using a custom signup form would be the better thing to do.

**Comment by mateusz-sikora** [comment]
@ThomasGrzybowski Are you sure you are sending **POST** request to correct url?

You can also try `python manage.py show_urls` command from django extensions and make sure you have your urls configured properly.

**Comment by ThomasGrzybowski** [comment]
The file "../lib/python3.2/site-packages/allauth/account/urls.py" has the code:
urlpatterns = patterns(
    "",
    url(r"^signup/$", views.signup, name="account_signup"),

But I'm not sure how to expose the "/signup/" api url for use.  It would be helpful if this was implemented as part of the django-rest-auth distribution :-)

**Comment by mateusz-sikora** [comment]
But signup API is already exposed in `rest_auth.registration` app. Please see documentation http://django-rest-auth.readthedocs.org/en/latest/installation.html#registration-optional

If it doesn't help, please try out our demo project. This should be also very helpful http://django-rest-auth.readthedocs.org/en/latest/demo.html

**Comment by mateusz-sikora** [comment]
@ThomasGrzybowski Did you figure out what was causing your issue? Was it improper configuration or something else?

**Comment by ThomasGrzybowski** [comment]
The demo works fine with the /signup/ url. From the documentation I was
expecting to use /register/ for use with the angular-django-registration-auth
client.

From what I can tell, angular-django-registration-auth does not yet support
/signup/.


Thanks for your support,
Tom

**Comment by mateusz-sikora** [comment]
I'm confused. I think you are mixing up two urls. `/signup/` from demo project is for serving template with signup form and inside this template you can find a form which send a POST request to `/rest-auth/registration/` where django-rest-auth registration is handled.

Here are all urls from demo project https://github.com/Tivix/django-rest-auth/blob/master/demo/demo/urls.py

In my opinion if you still have this issue:

> But when I attempt to use the /registration/ api url "http://localhost:8000/rest-auth/registration/", I get HTTP 405 METHOD NOT ALLOWED

then I think you still have improper url configuration and it's not an issue in django-rest-auth.

**Comment by pravin-d** [comment]
@ThomasGrzybowski Check this link out [this](http://tech.agilitynerd.com/django-rest-registration-with-django-rest-auth.html) Not sure if this is the case. The user is actually registered but you get a traceback error

**Comment by kimutaiRop** [comment]
I think this issue was closed even b4 it was solved I have the same issue using react and django, when i signup with rest-framework registration then it works but if i use axios to post data to django from localhost:8000 then it gives error Forbidden: /rest-auth/registration/
but using localhost:3000 which is the pure react with exact same code the user is registered, i came to believe that at the localhost:8000 django is trying to get the session key that is not suppose to even be getting since my authentication is suppose to be using token authentication
if this issue is to be delt with, someone to try using the restauth one page app like react front end under the django server port 8000 and see the error they are getting
