### ISSUE TITLE
How to create extended user Profile?

### ISSUE THREAD

**Issue by SiddharthMantri** [Tivix/django-rest-auth#58]
I've created the following user serializer for when the user signs up

    class UserSignUpSerializer(serializers.ModelSerializer):
        class Meta:
            model = User
            fields = ('email',)

        def create(self, validated_data):
            user = User(email=validated_data['email'], username=validated_data['email'])
            user.set_password(validated_data['password'])
            user.save()
            profile = UserProfile(user=user)
            profile.save()
            return user

However, this doesn't create a new UserProfile that's associated with the User model.

My UserProfile model is defined as follows:

    class UserProfile(models.Model):
        user = models.OneToOneField(User)
        #Some Fields for UserProfile

**Comment by mateusz-sikora** [comment]
Please take a look at point number 2 on FAQ page http://django-rest-auth.readthedocs.org/en/latest/faq.html

**Comment by SiddharthMantri** [comment]
This is for updating. However, doesn't work for create UserProfile.

**Comment by mateusz-sikora** [comment]
So you need to customize signup form in django-allauth.

See django-allauth documetation (`ACCOUNT_SIGNUP_FORM_CLASS`) http://django-allauth.readthedocs.org/en/latest/configuration.html
