### ISSUE TITLE
Is this Repository Still maintained?

### ISSUE THREAD

**Issue by Aniket-Singla** [Tivix/django-rest-auth#580]
Hello , I started using this package because it provided support for django-allauth for social media authentication. But since it's seven months since last commit, I wanted to ask whether this package is still maintained or not? There are many flaws in the documentation and jwt usage is one of them. The documentation as well as the package is not update till now even after the anouncement of djangorestframework-jwt being depricated and moved. I wanted to ask all the folks out there should I continue using this package in my development or should I shift to other packages like Djoser or should I write my own views dealing with social media authentication. Sorry for asking a question in the issues section.

**Comment by rpkilby** [comment]
Hi @Aniket-Singla. The repo is currently on pause. See #568.
