### ISSUE TITLE
rest-auth/login returns {"detail":"CSRF Failed: CSRF cookie not set."}

### ISSUE THREAD

**Issue by redcricket** [Tivix/django-rest-auth#586]
Hi,

I have been trying to integrate React.js application to a Django server that has django-rest-auth installed.  The details of my question are here: https://stackoverflow.com/questions/59095076/dango-react-axios-and-csrf-failed-csrf-token-missing-or-incorrect
Thank you

**Comment by redcricket** [comment]
oops it was something I was doing wrong

**Comment by AnupamBrt** [comment]
Can you mention what you were doing wrong? I am currently facing the same issue.

**Comment by mitorski** [comment]
@redcricket I would also know, what are you doing wrong.

**Comment by nielsuit227** [comment]
@redcricket @AnupamBrt @mitorski ever figured it out?
