### ISSUE TITLE
Session cookie age for Facebook Rest Auth

### ISSUE THREAD

**Issue by SiddharthMantri** [Tivix/django-rest-auth#60]
It seems like the session for facebook auth lasts only a few hours.  Is there a default `Session_cookie_age` setting that I can override in `settings.py` with regards to rest_auth? As far as I know, Django's default cookie age is 2 weeks so that shouldn't be whats causing this issue,right?

**Comment by mateusz-sikora** [comment]
In both login views: standard login and social login which actually inherit standard login, we use django login function from `django.contrib.auth` so all session settings depends on django configuration.

Are you sure you didn't lose session id from cookies during these few hours when you have been logged out from facebook?

**Comment by SiddharthMantri** [comment]
Is there any way I can test this? As what you said makes sense and I may be losing the session id. Or i've implemented Facebook auth on the front end in an incorrect manner. I'll test that.

**Comment by SiddharthMantri** [comment]
I was just checking Facebooks response and it seems like they give me a access token that expires in 64 minutes. Could that be the issue?

**Comment by mariodev** [comment]
@SiddharthMantri I think that may be it, you probably getting a short-lived token, which is described here: https://developers.facebook.com/docs/facebook-login/access-tokens/expiration-and-extension
