### ISSUE TITLE
Failed Authentication Should Result in HTTP 401

### ISSUE THREAD

**Issue by riggsd** [Tivix/django-rest-auth#62]
I've got `django-rest-auth` 0.3.4 and `django-rest-framework` 3.1.0 configured and working correctly with TokenAuth on `Django` 1.8c1.

However, I note that when providing incorrect username/password to the `api/rest-auth/login` endpoint, it responds with `HTTP 400` (Bad Request).

It seems that the correct status code, and the one most consistent with [Rest Framework auth docs](http://www.django-rest-framework.org/api-guide/authentication/#unauthorized-and-forbidden-responses), would be `HTTP 401` (Unauthorized).

**Comment by mjaworski** [comment]
The authorization endpoint does not require authorization, which is what a 401 response is meant to indicate. 401 indicates to the client that the Authorization must already be set. That is never necessary when making a request to the authorization endpoint. Therefore, 400 Bad Request is still the most appropriate response when invalid credentials are supplied.
