### ISSUE TITLE
PasswordReset requires django.contrib.auth urls

### ISSUE THREAD

**Issue by svleeuwen** [Tivix/django-rest-auth#63]
The PasswordReset view depends on `django.contrib.auth.views.password_reset_confirm`. Therefore we need `url(r'^', include('django.contrib.auth.urls')),` in urlpatterns.
As I'm using django-allauth this wasn't the case in my situation.
Maybe this could be added to the docs.

When using allauth it doesn't make sense to use the default django auth views right?
Should I overwrite all PasswordReset views and serializers to implement the allauth 'way' of dealing with password resets?

**Comment by mjaworski** [comment]
The PasswordReset view uses PasswordResetSerializer which by default uses django's PasswordResetForm, if you want to change the default behavior, you should supply your own serializer which can be done in the settings of your django project: http://django-rest-auth.readthedocs.org/en/latest/configuration.html

**Comment by philippeluickx** [comment]
+1 in clarifying this.

**Comment by holms** [comment]
:+1:  please include this in the docs somehow.. your tests been failing without this include

**Comment by aspectmkn8rd** [comment]
ty, it helped me.

**Comment by diegobill** [comment]
+1

**Comment by latusaki** [comment]
Any reason this is not in the installation documentation ?
Should I make a PR ?

**Comment by Kaspler** [comment]
I suggest a simpler and more secure solution: https://stackoverflow.com/a/53636611/1254540
