### ISSUE TITLE
Google social auth

### ISSUE THREAD

**Issue by nadhem-zmandar** [Tivix/django-rest-auth#637]
I am trying to implement the social auth using google as provider. I created a google app , added my credentials on the admin social app  and  followed the same steps mentionned on the documentation (Facebook example). But I didn't understand how can I  get acces token to test the Api ?

**Comment by PascalOtto** [comment]
if I understand your question correctly, you want an access token for testing. You can get it at https://developers.google.com/oauthplayground

**Comment by nadhem-zmandar** [comment]
@PascalOtto  Absolutely , this is what I am looking for.
Many thanks
