### ISSUE TITLE
deleted a user 

### ISSUE THREAD

**Issue by zombiecong** [Tivix/django-rest-auth#71]
OperationalError at /admin/auth/user/3/delete/
no such table: allauth_socialaccount
Request Method:	GET
Request URL:	http://127.0.0.1:8888/admin/auth/user/3/delete/
Django Version:	1.8
Exception Type:	OperationalError
Exception Value:	
no such table: allauth_socialaccount
Exception Location:	/home/coco/project/env/jifen/lib/python3.4/site-packages/Django-1.8-py3.4.egg/django/db/backends/sqlite3/base.py in execute, line 318
Python Executable:	/home/coco/project/env/jifen/bin/python
Python Version:	3.4.0
Python Path:	
['/home/coco/project/django-rest-auth/demo',
 '/home/coco/project/env/jifen/lib/python3.4/site-packages/Django-1.8-py3.4.egg',
 '/home/coco/project/env/jifen/lib/python3.4',
 '/home/coco/project/env/jifen/lib/python3.4/plat-x86_64-linux-gnu',
 '/home/coco/project/env/jifen/lib/python3.4/lib-dynload',
 '/usr/lib/python3.4',
 '/usr/lib/python3.4/plat-x86_64-linux-gnu',
 '/home/coco/project/env/jifen/lib/python3.4/site-packages']
Server time:	Mon, 13 Apr 2015 06:14:38 +0000

**Comment by zombiecong** [comment]
i didnt use the socialaccount

**Comment by mateusz-sikora** [comment]
Can you paste here a list of all installed applications in your project?

I think you have socialaccount added in you installed apps and you haven't called `./manage.py migrate` yet. http://django-allauth.readthedocs.org/en/latest/installation.html#post-installation

Anyway, that's not an django-rest-auth issue.

**Comment by nickspacek** [comment]
Here's my list of apps:

'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'rest_framework',
    'rest_framework.authtoken',
    'rest_auth',
    'allauth',
    'allauth.account',
    'rest_auth.registration',

I'm getting this error as well. I haven't included allauth.socialaccount as it was listed as optional, but when I delete a user I get this error as well.

**Comment by nickspacek** [comment]
I tracked down this bug, it is due to [registration/serializers.py#L7](https://github.com/Tivix/django-rest-auth/blob/v0.5.0/rest_auth/registration/serializers.py#L7). This line of code ends up registering the SocialAccount model which adds the ForeignKey to User.

**Comment by webcodestar** [comment]
Add this into  list of apps:
    'allauth.socialaccount',
And, please try migrate again.
I have fixed same issue like above way.
