### ISSUE TITLE
Consistent responses (and docs)

### ISSUE THREAD

**Issue by philippeluickx** [Tivix/django-rest-auth#74]
I am a bit confused on which responses each endpoint provides, in terms of JWT and user data.

Register sends back the user data from the UserDetailsSerializer, but no token.
Login in turn sends back the JWT, but no  user data.

Is it possible to have both being returned in case of register and login?

**Comment by mariodev** [comment]
At this point, in both cases, the token key is being returned using `TokenSerializer`. You can always override it to include related user.
