### ISSUE TITLE
SocialLogin should catch the case that the email exists

### ISSUE THREAD

**Issue by yarbelk** [Tivix/django-rest-auth#83]
If there exists a login with an email (eg - from  a username/password) and you login with a social account - you can get a database error if you have uniqueness constraints on your User email

There should be a HTTP_409_conflict raised here on DB error - That email exists.

https://github.com/Tivix/django-rest-auth/blob/master/rest_auth/registraton/serializers.py#42

**Comment by Antwan86** [comment]
This should be normally [get caught](https://github.com/pennersr/django-allauth/blob/master/allauth/socialaccount/adapter.py#L136) by allauth library.

**Comment by maxim-kht** [comment]
Resolved in https://github.com/Tivix/django-rest-auth/pull/367
