### ISSUE TITLE
Facebook access_token

### ISSUE THREAD

**Issue by netxone** [Tivix/django-rest-auth#84]
A question about social authentication in a mobile app. After user has just logged using browser to accounts/facebook/login /, the instance with the access_token is created in the social application table. Now, i need to get this access_token for sending POST request to rest-auth/facebook/ but there is no endpoint for it. How can i get it?

**Comment by italomaia** [comment]
You mean this? http://django-rest-auth.readthedocs.org/en/latest/installation.html#social-authentication-optional

**Comment by Antwan86** [comment]
The way it's designed is meant that the client have to request the auth_token on its own, so it must know the client_secret/client_id, therefore this is only suitable for native apps clients.

**Comment by netxone** [comment]
ok, as I had supposed. Thanks
