### ISSUE TITLE
Undeclared dependency of rest_auth.registration on allauth.socialaccount

### ISSUE THREAD

**Issue by jhogg41** [Tivix/django-rest-auth#86]
To see this happen use only allauth and allauth.account in INSTALLED APPS then try and delete a user through the admin interface - it complains about a non existant table. Commenting out the url include for rest_auth.registration.urls makes the resultant error disappear.

Seems to be caused by import in rest_auth/registration/serializers.py:
from allauth.socialaccount.helpers import complete_social_login

Commenting the above line and all refs to complete_social_login removes the error.

Proper workaround probably involves some form of selective importing based on configuration or not of social logins in a similar way to allauth gets around the problem.

**Comment by erj1** [comment]
+1 -- I am running into this exact issue.

**Comment by citizen-stig** [comment]
@jhogg41 I've noticed similar problem. If you're comment the allauth urls and tries to do login using twitter it will give you a url reverse. 
The problem.
```rest_auth/registration/serializers.py:38``` => calls ```complete_social_login(request, login)```

=> ```allauth.socialaccount.helpers.py:129```, definition of ```complete_social_login```, than 

=> ```allauth.socialaccount.helpers.py:145```,  calls ```_complete_social_login(request, sociallogin)````

=> ```allauth.socialaccount.helpers.py:153```, definition of ```_complete_social_login(request, sociallogin)````

=>  ```allauth.socialaccount.helpers.py:161```, calls ```_process_signup(request, sociallogin)```

=> ```allauth.socialaccount.helpers.py:23```, definion of ```_process_signup(request, sociallogin)```

and here ```allauth.socialaccount.helpers.py:28``` we have ```url = reverse('socialaccount_signup')```

which fails if you don't include the allauth.urls in your urls.py. 

Furthermore, the  ```rest_auth/registration/serializers.py:38``` ignores the returned response
