### ISSUE TITLE
Feature Request: dynamically configurable activate_url with registration

### ISSUE THREAD

**Issue by jhogg41** [Tivix/django-rest-auth#87]
So using rest_auth.registration is great. However the emails sent out by django-allauth are less than useful. allauth sends out a nice email telling users to confirm their email address. However the activation url is django related and doesn't match the allauth endpoint either.

The way to fix this in allauth is just to declare another route with the correct reverse() name. This doesn't work if we want to target a static page in our angular app however!

It would be really nice if rest_auth overrode the activation url with a setting, possibly by replacing the relevant allauth view (don't know if that will work or not).

Thanks for all the hard work!

**Comment by deecodameeko** [comment]
I second this request.

**Comment by deecodameeko** [comment]
Actually what I've found is that the verification key is avaiable to your template, so you can simple override the allauth account email and customize it to reference the key like so http://yoursite/your/path/to/spa/app/{{key}}

**Comment by jrivera294** [comment]
Maybe this will help you: http://django-allauth.readthedocs.org/en/latest/advanced.html#custom-redirects

I needed to use a different email API and I had to modify the send_mail function. maybe you just need to modify the function that generates the url.

**Comment by jvgelder** [comment]
I think this is what he is looking for: http://stackoverflow.com/questions/28461653/how-to-change-the-value-of-activate-url-in-django-allauth

Might want to add that answer to the documentation.

**Comment by philippeluickx** [comment]
+1

**Comment by jberends** [comment]
+1 strange that this is not an external settable configuration, but that you need to do trickeries. It resolves to 'localhost' for me in projects.

**Comment by mariodev** [comment]
Added to FAQ page. Closing.
