### ISSUE TITLE
Error with required email

### ISSUE THREAD

**Issue by awwester** [Tivix/django-rest-auth#89]
On user registration after upgrading to 0.4.0 I'm getting an error:  AssertionError: May not set both `read_only` and `required`

which is being raised in django rest framework fields.py line 183 assert not (read_only and required), NOT_READ_ONLY_REQUIRED.

This is because the email field is being marked read_only in rest_auth.serializers.UserDetailsSerializer, and I'm not sure why. When I get rid of that line the error goes away.

Should the email only be marked read_only if it's not required since it can't be required and read_only?

I'm getting this error with rest_auth version 0.4.0, django 1.8.3, DRF 3.1.3.

**Comment by mariodev** [comment]
Can you please confirm if this issue still exists for 0.5.0 and above? Thanks!
