### ISSUE TITLE
[BUG] request.DATA usage removed in Django Rest Framework 3.2

### ISSUE THREAD

**Issue by erj1** [Tivix/django-rest-auth#96]
Using django-rest-auth 4.0, and upgraded to djangorestframework 3.2 and received the following exception when testing the registration route:

> NotImplementedError at /rest-auth/registration/
> `request.DATA` has been deprecated in favor of `request.data` since version 3.0, and has been fully removed as of version 3.2.

request.DATA is appears to be called from **rest_framework/request.py line 40**.

**Comment by JeansReal** [comment]
Hi!, yes the same bug here
on views.py

class Login(GenericAPIView):
    def post(self, request, *args, **kwargs):
        self.serializer = self.get_serializer(data=self.request.DATA) # This line request.DATA

**Comment by illing2005** [comment]
There is already a pull request by @alacritythief solving this. 
https://github.com/Tivix/django-rest-auth/pull/94

**Comment by erj1** [comment]
Thanks.

**Comment by gladsonvm** [comment]
Is pip package updated on this issue?

**Comment by holms** [comment]
C'mon I have the same issue, this version is unsable with django-tests at all.

**Comment by gladsonvm** [comment]
I followed stack trace of error and just replaced request.DATA with request.data in those files which generated errors as per the stack trace. Then It worked fine for me. However I dont know whether it is compatible with django-tests. May be request.DATA have to be replaced with request.data for django-tests.

**Comment by holms** [comment]
Ok it does work from master branch, putting git repo link to requirements.txt solved it.
