### ISSUE TITLE
Is a release for django-rest-auth planned for the near future?

### ISSUE THREAD

**Issue by daynemay** [Tivix/django-rest-auth#99]
I ask because I'm hoping to be able to update and get commit 02bf6fb, because I want to update `django-rest-framework` to 3.2.0 as soon as possible.

**Comment by bryancusatis** [comment]
Would also like a release for the same feature + username-less login. Thanks!

**Comment by cmdelatorre** [comment]
+1 to this request, for both reasons: django-rest-framework@3.2.0 and email-based login

**Comment by amadornimbis** [comment]
+1 for both of the reasons mentioned in the OP

**Comment by ceelian** [comment]
+1

**Comment by mateusz-sikora** [comment]
Done :rocket:
